// Code generated by Fern. DO NOT EDIT.

package client

import (
	context "context"

	extend "github.com/extend-hq/extend-go-sdk"
	batchprocessorrun "github.com/extend-hq/extend-go-sdk/batchprocessorrun"
	batchruns "github.com/extend-hq/extend-go-sdk/batchruns"
	classifiers "github.com/extend-hq/extend-go-sdk/classifiers"
	classifierversions "github.com/extend-hq/extend-go-sdk/classifierversions"
	classifyruns "github.com/extend-hq/extend-go-sdk/classifyruns"
	core "github.com/extend-hq/extend-go-sdk/core"
	editruns "github.com/extend-hq/extend-go-sdk/editruns"
	editschemas "github.com/extend-hq/extend-go-sdk/editschemas"
	edittemplates "github.com/extend-hq/extend-go-sdk/edittemplates"
	evaluationsetitems "github.com/extend-hq/extend-go-sdk/evaluationsetitems"
	evaluationsetruns "github.com/extend-hq/extend-go-sdk/evaluationsetruns"
	evaluationsets "github.com/extend-hq/extend-go-sdk/evaluationsets"
	extractors "github.com/extend-hq/extend-go-sdk/extractors"
	extractorversions "github.com/extend-hq/extend-go-sdk/extractorversions"
	extractruns "github.com/extend-hq/extend-go-sdk/extractruns"
	files "github.com/extend-hq/extend-go-sdk/files"
	internal "github.com/extend-hq/extend-go-sdk/internal"
	option "github.com/extend-hq/extend-go-sdk/option"
	parseruns "github.com/extend-hq/extend-go-sdk/parseruns"
	processor "github.com/extend-hq/extend-go-sdk/processor"
	processorrun "github.com/extend-hq/extend-go-sdk/processorrun"
	processorversion "github.com/extend-hq/extend-go-sdk/processorversion"
	splitruns "github.com/extend-hq/extend-go-sdk/splitruns"
	splitters "github.com/extend-hq/extend-go-sdk/splitters"
	splitterversions "github.com/extend-hq/extend-go-sdk/splitterversions"
	webhookendpoints "github.com/extend-hq/extend-go-sdk/webhookendpoints"
	webhooksubscriptions "github.com/extend-hq/extend-go-sdk/webhooksubscriptions"
	workflowruns "github.com/extend-hq/extend-go-sdk/workflowruns"
	workflows "github.com/extend-hq/extend-go-sdk/workflows"
	workflowversions "github.com/extend-hq/extend-go-sdk/workflowversions"
)

type Client struct {
	WithRawResponse      *RawClient
	Files                *files.Client
	ParseRuns            *parseruns.Client
	EditRuns             *editruns.Client
	EditTemplates        *edittemplates.Client
	EditSchemas          *editschemas.Client
	ExtractRuns          *extractruns.Client
	Extractors           *extractors.Client
	ExtractorVersions    *extractorversions.Client
	ClassifyRuns         *classifyruns.Client
	Classifiers          *classifiers.Client
	ClassifierVersions   *classifierversions.Client
	SplitRuns            *splitruns.Client
	Splitters            *splitters.Client
	SplitterVersions     *splitterversions.Client
	Workflows            *workflows.Client
	WorkflowVersions     *workflowversions.Client
	WorkflowRuns         *workflowruns.Client
	ProcessorRun         *processorrun.Client
	Processor            *processor.Client
	ProcessorVersion     *processorversion.Client
	BatchProcessorRun    *batchprocessorrun.Client
	BatchRuns            *batchruns.Client
	EvaluationSets       *evaluationsets.Client
	EvaluationSetItems   *evaluationsetitems.Client
	EvaluationSetRuns    *evaluationsetruns.Client
	WebhookEndpoints     *webhookendpoints.Client
	WebhookSubscriptions *webhooksubscriptions.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Files:                files.NewClient(options),
		ParseRuns:            parseruns.NewClient(options),
		EditRuns:             editruns.NewClient(options),
		EditTemplates:        edittemplates.NewClient(options),
		EditSchemas:          editschemas.NewClient(options),
		ExtractRuns:          extractruns.NewClient(options),
		Extractors:           extractors.NewClient(options),
		ExtractorVersions:    extractorversions.NewClient(options),
		ClassifyRuns:         classifyruns.NewClient(options),
		Classifiers:          classifiers.NewClient(options),
		ClassifierVersions:   classifierversions.NewClient(options),
		SplitRuns:            splitruns.NewClient(options),
		Splitters:            splitters.NewClient(options),
		SplitterVersions:     splitterversions.NewClient(options),
		Workflows:            workflows.NewClient(options),
		WorkflowVersions:     workflowversions.NewClient(options),
		WorkflowRuns:         workflowruns.NewClient(options),
		ProcessorRun:         processorrun.NewClient(options),
		Processor:            processor.NewClient(options),
		ProcessorVersion:     processorversion.NewClient(options),
		BatchProcessorRun:    batchprocessorrun.NewClient(options),
		BatchRuns:            batchruns.NewClient(options),
		EvaluationSets:       evaluationsets.NewClient(options),
		EvaluationSetItems:   evaluationsetitems.NewClient(options),
		EvaluationSetRuns:    evaluationsetruns.NewClient(options),
		WebhookEndpoints:     webhookendpoints.NewClient(options),
		WebhookSubscriptions: webhooksubscriptions.NewClient(options),
		WithRawResponse:      NewRawClient(options),
		options:              options,
		baseURL:              options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Parse a file synchronously, waiting for the result before returning. This endpoint has a **5-minute timeout** — if processing takes longer, the request will fail.
//
// **Note:** This endpoint is intended for onboarding and testing only. For production workloads, use `POST /parse_runs` with [polling or webhooks](https://docs.extend.ai/2026-02-09/developers/async-processing) instead, as it provides better reliability for large files and avoids timeout issues.
//
// The Parse endpoint allows you to convert documents into structured, machine-readable formats with fine-grained control over the parsing process. This endpoint is ideal for extracting cleaned document content to be used as context for downstream processing, e.g. RAG pipelines, custom ingestion pipelines, embeddings classification, etc.
//
// For more details, see the [Parse File guide](https://docs.extend.ai/2026-02-09/product/parsing/parse).
func (c *Client) Parse(
	ctx context.Context,
	request *extend.ParseRequest,
	opts ...option.RequestOption,
) (*extend.ParseRun, error) {
	response, err := c.WithRawResponse.Parse(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Edit a file synchronously, waiting for the result before returning. This endpoint has a **5-minute timeout** — if processing takes longer, the request will fail.
//
// **Note:** This endpoint is intended for onboarding and testing only. For production workloads, use `POST /edit_runs` with [polling or webhooks](https://docs.extend.ai/2026-02-09/developers/async-processing) instead, as it provides better reliability for large files and avoids timeout issues.
//
// The Edit endpoint allows you to detect and fill form fields in PDF documents.
//
// For more details, see the [Edit File guide](https://docs.extend.ai/2026-02-09/product/editing/edit).
func (c *Client) Edit(
	ctx context.Context,
	request *extend.EditRequest,
	opts ...option.RequestOption,
) (*extend.EditRun, error) {
	response, err := c.WithRawResponse.Edit(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Extract structured data from a file synchronously, waiting for the result before returning. This endpoint has a **5-minute timeout** — if processing takes longer, the request will fail.
//
// **Note:** This endpoint is intended for onboarding and testing only. For production workloads, use `POST /extract_runs` with [polling or webhooks](https://docs.extend.ai/2026-02-09/developers/async-processing) instead, as it provides better reliability for large files and avoids timeout issues.
//
// The Extract endpoint allows you to extract structured data from files using an existing extractor or an inline configuration.
//
// For more details, see the [Extract File guide](https://docs.extend.ai/2026-02-09/product/extraction/quick-start-5-minutes).
func (c *Client) Extract(
	ctx context.Context,
	request *extend.ExtractRequest,
	opts ...option.RequestOption,
) (*extend.ExtractRun, error) {
	response, err := c.WithRawResponse.Extract(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Classify a document synchronously, waiting for the result before returning. This endpoint has a **5-minute timeout** — if processing takes longer, the request will fail.
//
// **Note:** This endpoint is intended for onboarding and testing only. For production workloads, use `POST /classify_runs` with [polling or webhooks](https://docs.extend.ai/2026-02-09/developers/async-processing) instead, as it provides better reliability for large files and avoids timeout issues.
//
// The Classify endpoint allows you to classify documents using an existing classifier or an inline configuration.
//
// For more details, see the [Classify File guide](https://docs.extend.ai/2026-02-09/product/classification/configuring-a-classifier).
func (c *Client) Classify(
	ctx context.Context,
	request *extend.ClassifyRequest,
	opts ...option.RequestOption,
) (*extend.ClassifyRun, error) {
	response, err := c.WithRawResponse.Classify(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Split a document synchronously, waiting for the result before returning. This endpoint has a **5-minute timeout** — if processing takes longer, the request will fail.
//
// **Note:** This endpoint is intended for onboarding and testing only. For production workloads, use `POST /split_runs` with [polling or webhooks](https://docs.extend.ai/2026-02-09/developers/async-processing) instead, as it provides better reliability for large files and avoids timeout issues.
//
// The Split endpoint allows you to split documents into multiple parts using an existing splitter or an inline configuration.
//
// For more details, see the [Split File guide](https://docs.extend.ai/2026-02-09/product/splitting/configuring-a-splitter).
func (c *Client) Split(
	ctx context.Context,
	request *extend.SplitRequest,
	opts ...option.RequestOption,
) (*extend.SplitRun, error) {
	response, err := c.WithRawResponse.Split(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
