// Code generated by Fern. DO NOT EDIT.

package parseruns

import (
	context "context"

	extend "github.com/extend-hq/extend-go-sdk"
	core "github.com/extend-hq/extend-go-sdk/core"
	internal "github.com/extend-hq/extend-go-sdk/internal"
	option "github.com/extend-hq/extend-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// List parse runs, with optional filters for status, batch ID, source, and file name.
//
// Returns a paginated list of parse runs. Use `GET /parse_runs/{id}` to retrieve the full result including output for a specific run.
func (c *Client) List(
	ctx context.Context,
	request *extend.ParseRunsListRequest,
	opts ...option.RequestOption,
) (*extend.ParseRunsListResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Parse files to get cleaned, chunked target content (e.g. markdown).
//
// The Parse endpoint allows you to convert documents into structured, machine-readable formats with fine-grained control over the parsing process. This endpoint is ideal for extracting cleaned document content to be used as context for downstream processing, e.g. RAG pipelines, custom ingestion pipelines, embeddings classification, etc.
//
// The request returns immediately with a `PROCESSING` status. Use webhooks or poll the Get Parse Run endpoint for results.
func (c *Client) Create(
	ctx context.Context,
	request *extend.ParseRunsCreateRequest,
	opts ...option.RequestOption,
) (*extend.ParseRun, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve the status and results of a parse run.
//
// Use this endpoint to get results for a parse run that has already completed, or to check on the status of a parse run initiated by the [Create Parse Run](https://docs.extend.ai/2026-02-09/developers/api-reference/endpoints/parse/create-parse-run) endpoint.
func (c *Client) Retrieve(
	ctx context.Context,
	// The unique identifier for the parse run.
	//
	// Example: `"pr_xK9mLPqRtN3vS8wF5hB2cQ"`
	id string,
	request *extend.ParseRunsRetrieveRequest,
	opts ...option.RequestOption,
) (*extend.ParseRun, error) {
	response, err := c.WithRawResponse.Retrieve(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete a parse run and all associated data from Extend. This operation is permanent and cannot be undone.
//
// This endpoint can be used if you'd like to manage data retention on your own rather than automated data retention policies. Or make one-off deletions for your downstream customers.
func (c *Client) Delete(
	ctx context.Context,
	// The ID of the parse run to delete.
	//
	// Example: `"pr_xK9mLPqRtN3vS8wF5hB2cQ"`
	id string,
	request *extend.ParseRunsDeleteRequest,
	opts ...option.RequestOption,
) (*extend.ParseRunsDeleteResponse, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Submit up to **1,000 files** for parsing in a single request. Each file is processed as an independent parse run using the same configuration.
//
// Unlike the single [Parse File (Async)](https://docs.extend.ai/2026-02-09/developers/api-reference/endpoints/parse/create-parse-run) endpoint, this batch endpoint accepts an `inputs` array and immediately returns a `BatchRun` object containing a batch `id` and a `PENDING` status. The individual runs are then queued and processed asynchronously.
//
// **Monitoring results:**
// - **Webhooks (recommended):** Subscribe to `batch_parse_run.processed` and `batch_parse_run.failed` events. The webhook payload indicates the batch has finished — fetch individual run results using `GET /parse_runs?batchId={id}`.
// - **Polling:** Call `GET /batch_runs/{id}` to check the overall batch status, and use `GET /parse_runs?batchId={id}` to retrieve individual run results.
//
// **Notes:**
// - `inputs` must contain between 1 and 1,000 items.
// - File input supports URLs, Extend file IDs, and raw text strings.
func (c *Client) CreateBatch(
	ctx context.Context,
	request *extend.ParseRunsCreateBatchRequest,
	opts ...option.RequestOption,
) (*extend.BatchRun, error) {
	response, err := c.WithRawResponse.CreateBatch(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
