// Code generated by Fern. DO NOT EDIT.

package classifierversions

import (
	context "context"

	extend "github.com/extend-hq/extend-go-sdk"
	core "github.com/extend-hq/extend-go-sdk/core"
	internal "github.com/extend-hq/extend-go-sdk/internal"
	option "github.com/extend-hq/extend-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// This endpoint allows you to fetch all versions of a given classifier, including the current `draft` version.
//
// Versions are returned in descending order of creation (newest first) with the `draft` version first. The `draft` version is the latest unpublished version of the classifier, which can be published to create a new version. It might not have any changes from the last published version.
func (c *Client) List(
	ctx context.Context,
	// The ID of the classifier.
	//
	// Example: `"cl_Xj8mK2pL9nR4vT7qY5wZ"`
	classifierID string,
	request *extend.ClassifierVersionsListRequest,
	opts ...option.RequestOption,
) (*extend.ClassifierVersionsListResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		classifierID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// This endpoint allows you to publish a new version of an existing classifier. Publishing a new version creates a snapshot of the classifier's current configuration and makes it available for use in workflows.
//
// Publishing a new version does not automatically update existing workflows using this classifier. You may need to manually update workflows to use the new version if desired.
func (c *Client) Create(
	ctx context.Context,
	// The ID of the classifier.
	//
	// Example: `"cl_Xj8mK2pL9nR4vT7qY5wZ"`
	classifierID string,
	request *extend.ClassifierVersionsCreateRequest,
	opts ...option.RequestOption,
) (*extend.ClassifierVersion, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		classifierID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve a specific version of a classifier in Extend
func (c *Client) Retrieve(
	ctx context.Context,
	// The ID of the classifier.
	//
	// Example: `"cl_Xj8mK2pL9nR4vT7qY5wZ"`
	classifierID string,
	// The version to retrieve. Accepts any of the following:
	//
	// - `"draft"` — returns the current draft version
	// - `"latest"` — returns the latest published version (falls back to draft if none published)
	// - A version number (e.g. `"0.1"`, `"1.0"`) — returns that specific published version
	// - A version ID (e.g. `"clsv_QYk6jgHA_8CsO8rVWhyNC"`) — returns that specific version by ID
	versionID string,
	request *extend.ClassifierVersionsRetrieveRequest,
	opts ...option.RequestOption,
) (*extend.ClassifierVersion, error) {
	response, err := c.WithRawResponse.Retrieve(
		ctx,
		classifierID,
		versionID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
