// Code generated by Fern. DO NOT EDIT.

package evaluationsetruns

import (
	context "context"

	extend "github.com/extend-hq/extend-go-sdk"
	core "github.com/extend-hq/extend-go-sdk/core"
	internal "github.com/extend-hq/extend-go-sdk/internal"
	option "github.com/extend-hq/extend-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Create and start an async evaluation set run. The response returns the evaluation set run object with its initial status; use `GET /evaluation_set_runs/{id}` to poll for completion.
//
// Evaluation set runs are currently supported for document processor evaluation sets.
func (c *Client) Create(
	ctx context.Context,
	request *extend.EvaluationSetRunsCreateRequest,
	opts ...option.RequestOption,
) (*extend.EvaluationSetRun, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get details of an evaluation set run.
func (c *Client) Retrieve(
	ctx context.Context,
	// The ID of the evaluation set run.
	//
	// Example: `"evr_Xj8mK2pL9nR4vT7qY5wZ"`
	id string,
	request *extend.EvaluationSetRunsRetrieveRequest,
	opts ...option.RequestOption,
) (*extend.EvaluationSetRun, error) {
	response, err := c.WithRawResponse.Retrieve(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
