// Code generated by Fern. DO NOT EDIT.

package extend

// Environments defines all of the API environments.
// These values can be used with the WithBaseURL
// RequestOption to override the client's default environment,
// if any.
var Environments = struct {
	Production    string
	ProductionUs2 string
	ProductionEu1 string
}{
	Production:    "https://api.extend.ai",
	ProductionUs2: "https://api.us2.extend.app",
	ProductionEu1: "https://api.eu1.extend.ai",
}
