// Code generated by Fern. DO NOT EDIT.

package extend

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/extend-hq/extend-go-sdk/internal"
	big "math/big"
)

var (
	filesDeleteRequestFieldExtendWorkspaceID = big.NewInt(1 << 0)
)

type FilesDeleteRequest struct {
	// The workspace ID to target. **Required** when using an organization-scoped API key; optional for workspace-scoped keys (the key is already tied to a workspace). See [Authentication](https://docs.extend.ai/2026-02-09/developers/authentication) for details on API key scopes.
	ExtendWorkspaceID *string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (f *FilesDeleteRequest) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetExtendWorkspaceID sets the ExtendWorkspaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesDeleteRequest) SetExtendWorkspaceID(extendWorkspaceID *string) {
	f.ExtendWorkspaceID = extendWorkspaceID
	f.require(filesDeleteRequestFieldExtendWorkspaceID)
}

var (
	filesListRequestFieldExtendWorkspaceID = big.NewInt(1 << 0)
	filesListRequestFieldNameContains      = big.NewInt(1 << 1)
	filesListRequestFieldSortDir           = big.NewInt(1 << 2)
	filesListRequestFieldNextPageToken     = big.NewInt(1 << 3)
	filesListRequestFieldMaxPageSize       = big.NewInt(1 << 4)
)

type FilesListRequest struct {
	// The workspace ID to target. **Required** when using an organization-scoped API key; optional for workspace-scoped keys (the key is already tied to a workspace). See [Authentication](https://docs.extend.ai/2026-02-09/developers/authentication) for details on API key scopes.
	ExtendWorkspaceID *string `json:"-" url:"-"`
	// Filters files to only include those that contain the given string in the name.
	//
	// Example: `"invoice"`
	NameContains  *string        `json:"-" url:"nameContains,omitempty"`
	SortDir       *SortDir       `json:"-" url:"sortDir,omitempty"`
	NextPageToken *NextPageToken `json:"-" url:"nextPageToken,omitempty"`
	MaxPageSize   *MaxPageSize   `json:"-" url:"maxPageSize,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (f *FilesListRequest) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetExtendWorkspaceID sets the ExtendWorkspaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesListRequest) SetExtendWorkspaceID(extendWorkspaceID *string) {
	f.ExtendWorkspaceID = extendWorkspaceID
	f.require(filesListRequestFieldExtendWorkspaceID)
}

// SetNameContains sets the NameContains field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesListRequest) SetNameContains(nameContains *string) {
	f.NameContains = nameContains
	f.require(filesListRequestFieldNameContains)
}

// SetSortDir sets the SortDir field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesListRequest) SetSortDir(sortDir *SortDir) {
	f.SortDir = sortDir
	f.require(filesListRequestFieldSortDir)
}

// SetNextPageToken sets the NextPageToken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesListRequest) SetNextPageToken(nextPageToken *NextPageToken) {
	f.NextPageToken = nextPageToken
	f.require(filesListRequestFieldNextPageToken)
}

// SetMaxPageSize sets the MaxPageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesListRequest) SetMaxPageSize(maxPageSize *MaxPageSize) {
	f.MaxPageSize = maxPageSize
	f.require(filesListRequestFieldMaxPageSize)
}

var (
	filesRetrieveRequestFieldExtendWorkspaceID = big.NewInt(1 << 0)
	filesRetrieveRequestFieldRawText           = big.NewInt(1 << 1)
	filesRetrieveRequestFieldMarkdown          = big.NewInt(1 << 2)
	filesRetrieveRequestFieldHTML              = big.NewInt(1 << 3)
)

type FilesRetrieveRequest struct {
	// The workspace ID to target. **Required** when using an organization-scoped API key; optional for workspace-scoped keys (the key is already tied to a workspace). See [Authentication](https://docs.extend.ai/2026-02-09/developers/authentication) for details on API key scopes.
	ExtendWorkspaceID *string `json:"-" url:"-"`
	// **Deprecated:** Use `POST /parse_runs` instead to parse file contents.
	//
	// If set to true, the raw text content of the file will be included in the response.
	RawText *bool `json:"-" url:"rawText,omitempty"`
	// **Deprecated:** Use `POST /parse_runs` instead to parse file contents.
	//
	// If set to true, the markdown content of the file will be included in the response.
	//
	// Only available for files with a type of PDF, IMG, or DOCX files that were auto-converted to PDFs.
	Markdown *bool `json:"-" url:"markdown,omitempty"`
	// **Deprecated:** Use `POST /parse_runs` instead to parse file contents.
	//
	// If set to true, the html content of the file will be included in the response.
	//
	// Only available for files with a type of DOCX.
	HTML *bool `json:"-" url:"html,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (f *FilesRetrieveRequest) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetExtendWorkspaceID sets the ExtendWorkspaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesRetrieveRequest) SetExtendWorkspaceID(extendWorkspaceID *string) {
	f.ExtendWorkspaceID = extendWorkspaceID
	f.require(filesRetrieveRequestFieldExtendWorkspaceID)
}

// SetRawText sets the RawText field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesRetrieveRequest) SetRawText(rawText *bool) {
	f.RawText = rawText
	f.require(filesRetrieveRequestFieldRawText)
}

// SetMarkdown sets the Markdown field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesRetrieveRequest) SetMarkdown(markdown *bool) {
	f.Markdown = markdown
	f.require(filesRetrieveRequestFieldMarkdown)
}

// SetHTML sets the HTML field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesRetrieveRequest) SetHTML(html *bool) {
	f.HTML = html
	f.require(filesRetrieveRequestFieldHTML)
}

var (
	filesDeleteResponseFieldID = big.NewInt(1 << 0)
)

type FilesDeleteResponse struct {
	// The ID of the deleted file.
	ID string `json:"id" url:"id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FilesDeleteResponse) GetID() string {
	if f == nil {
		return ""
	}
	return f.ID
}

func (f *FilesDeleteResponse) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FilesDeleteResponse) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesDeleteResponse) SetID(id string) {
	f.ID = id
	f.require(filesDeleteResponseFieldID)
}

func (f *FilesDeleteResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler FilesDeleteResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FilesDeleteResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FilesDeleteResponse) MarshalJSON() ([]byte, error) {
	type embed FilesDeleteResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FilesDeleteResponse) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

var (
	filesListResponseFieldData          = big.NewInt(1 << 0)
	filesListResponseFieldNextPageToken = big.NewInt(1 << 1)
)

type FilesListResponse struct {
	Data          []*FileSummary `json:"data" url:"data"`
	NextPageToken *NextPageToken `json:"nextPageToken,omitempty" url:"nextPageToken,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
	object         string

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FilesListResponse) GetData() []*FileSummary {
	if f == nil {
		return nil
	}
	return f.Data
}

func (f *FilesListResponse) GetNextPageToken() *NextPageToken {
	if f == nil {
		return nil
	}
	return f.NextPageToken
}

func (f *FilesListResponse) Object() string {
	return f.object
}

func (f *FilesListResponse) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FilesListResponse) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesListResponse) SetData(data []*FileSummary) {
	f.Data = data
	f.require(filesListResponseFieldData)
}

// SetNextPageToken sets the NextPageToken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesListResponse) SetNextPageToken(nextPageToken *NextPageToken) {
	f.NextPageToken = nextPageToken
	f.require(filesListResponseFieldNextPageToken)
}

func (f *FilesListResponse) UnmarshalJSON(data []byte) error {
	type embed FilesListResponse
	var unmarshaler = struct {
		embed
		Object string `json:"object"`
	}{
		embed: embed(*f),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*f = FilesListResponse(unmarshaler.embed)
	if unmarshaler.Object != "list" {
		return fmt.Errorf("unexpected value for literal on type %T; expected %v got %v", f, "list", unmarshaler.Object)
	}
	f.object = unmarshaler.Object
	extraProperties, err := internal.ExtractExtraProperties(data, *f, "object")
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FilesListResponse) MarshalJSON() ([]byte, error) {
	type embed FilesListResponse
	var marshaler = struct {
		embed
		Object string `json:"object"`
	}{
		embed:  embed(*f),
		Object: "list",
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FilesListResponse) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

var (
	filesUploadRequestFieldExtendWorkspaceID = big.NewInt(1 << 0)
	filesUploadRequestFieldConvertToPdf      = big.NewInt(1 << 1)
)

type FilesUploadRequest struct {
	// The workspace ID to target. **Required** when using an organization-scoped API key; optional for workspace-scoped keys (the key is already tied to a workspace). See [Authentication](https://docs.extend.ai/2026-02-09/developers/authentication) for details on API key scopes.
	ExtendWorkspaceID *string `json:"-" url:"-"`
	// When true, converts the uploaded file to PDF. Supported file types include images (JPEG, PNG, TIFF, GIF, BMP, WebP, HEIC/HEIF), Word documents, PowerPoint, Excel, and HTML.
	ConvertToPdf *bool `json:"-" url:"convertToPdf,omitempty"`
	// The password to unlock a password-protected PDF.
	Password *string `json:"password,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (f *FilesUploadRequest) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetExtendWorkspaceID sets the ExtendWorkspaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesUploadRequest) SetExtendWorkspaceID(extendWorkspaceID *string) {
	f.ExtendWorkspaceID = extendWorkspaceID
	f.require(filesUploadRequestFieldExtendWorkspaceID)
}

// SetConvertToPdf sets the ConvertToPdf field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FilesUploadRequest) SetConvertToPdf(convertToPdf *bool) {
	f.ConvertToPdf = convertToPdf
	f.require(filesUploadRequestFieldConvertToPdf)
}

func (f *FilesUploadRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler FilesUploadRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*f = FilesUploadRequest(body)
	return nil
}

func (f *FilesUploadRequest) MarshalJSON() ([]byte, error) {
	type embed FilesUploadRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}
