// Code generated by Fern. DO NOT EDIT.

package extend

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/extend-hq/extend-go-sdk/internal"
	big "math/big"
)

var (
	formDetectionRunsCreateRequestFieldFile   = big.NewInt(1 << 0)
	formDetectionRunsCreateRequestFieldConfig = big.NewInt(1 << 1)
)

type FormDetectionRunsCreateRequest struct {
	// The PDF form to analyze. Files can be provided as a URL or an Extend file ID.
	File   *FormDetectionRunsCreateRequestFile `json:"file" url:"-"`
	Config *EditSchemaGenerationConfig         `json:"config,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (f *FormDetectionRunsCreateRequest) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetFile sets the File field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FormDetectionRunsCreateRequest) SetFile(file *FormDetectionRunsCreateRequestFile) {
	f.File = file
	f.require(formDetectionRunsCreateRequestFieldFile)
}

// SetConfig sets the Config field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FormDetectionRunsCreateRequest) SetConfig(config *EditSchemaGenerationConfig) {
	f.Config = config
	f.require(formDetectionRunsCreateRequestFieldConfig)
}

func (f *FormDetectionRunsCreateRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler FormDetectionRunsCreateRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*f = FormDetectionRunsCreateRequest(body)
	return nil
}

func (f *FormDetectionRunsCreateRequest) MarshalJSON() ([]byte, error) {
	type embed FormDetectionRunsCreateRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	formDetectionRunsRetrieveRequestFieldExtendWorkspaceID = big.NewInt(1 << 0)
)

type FormDetectionRunsRetrieveRequest struct {
	// The workspace ID to target. **Required** when using an organization-scoped API key; optional for workspace-scoped keys (the key is already tied to a workspace). See [Authentication](https://docs.extend.ai/2026-02-09/api-reference/authentication) for details on API key scopes.
	ExtendWorkspaceID *string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (f *FormDetectionRunsRetrieveRequest) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetExtendWorkspaceID sets the ExtendWorkspaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FormDetectionRunsRetrieveRequest) SetExtendWorkspaceID(extendWorkspaceID *string) {
	f.ExtendWorkspaceID = extendWorkspaceID
	f.require(formDetectionRunsRetrieveRequestFieldExtendWorkspaceID)
}

// The PDF form to analyze. Files can be provided as a URL or an Extend file ID.
type FormDetectionRunsCreateRequestFile struct {
	FileFromURL *FileFromURL
	FileFromID  *FileFromID

	typ string
}

func (f *FormDetectionRunsCreateRequestFile) GetFileFromURL() *FileFromURL {
	if f == nil {
		return nil
	}
	return f.FileFromURL
}

func (f *FormDetectionRunsCreateRequestFile) GetFileFromID() *FileFromID {
	if f == nil {
		return nil
	}
	return f.FileFromID
}

func (f *FormDetectionRunsCreateRequestFile) UnmarshalJSON(data []byte) error {
	valueFileFromURL := new(FileFromURL)
	if err := json.Unmarshal(data, &valueFileFromURL); err == nil {
		f.typ = "FileFromURL"
		f.FileFromURL = valueFileFromURL
		return nil
	}
	valueFileFromID := new(FileFromID)
	if err := json.Unmarshal(data, &valueFileFromID); err == nil {
		f.typ = "FileFromID"
		f.FileFromID = valueFileFromID
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, f)
}

func (f FormDetectionRunsCreateRequestFile) MarshalJSON() ([]byte, error) {
	if f.typ == "FileFromURL" || f.FileFromURL != nil {
		return json.Marshal(f.FileFromURL)
	}
	if f.typ == "FileFromID" || f.FileFromID != nil {
		return json.Marshal(f.FileFromID)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", f)
}

type FormDetectionRunsCreateRequestFileVisitor interface {
	VisitFileFromURL(*FileFromURL) error
	VisitFileFromID(*FileFromID) error
}

func (f *FormDetectionRunsCreateRequestFile) Accept(visitor FormDetectionRunsCreateRequestFileVisitor) error {
	if f.typ == "FileFromURL" || f.FileFromURL != nil {
		return visitor.VisitFileFromURL(f.FileFromURL)
	}
	if f.typ == "FileFromID" || f.FileFromID != nil {
		return visitor.VisitFileFromID(f.FileFromID)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", f)
}
