// Code generated by Fern. DO NOT EDIT.

package extend

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersFormDetectionRunsCreateRequest(t *testing.T) {
	t.Run("SetFile", func(t *testing.T) {
		obj := &FormDetectionRunsCreateRequest{}
		var fernTestValueFile *FormDetectionRunsCreateRequestFile
		obj.SetFile(fernTestValueFile)
		assert.Equal(t, fernTestValueFile, obj.File)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetConfig", func(t *testing.T) {
		obj := &FormDetectionRunsCreateRequest{}
		var fernTestValueConfig *EditSchemaGenerationConfig
		obj.SetConfig(fernTestValueConfig)
		assert.Equal(t, fernTestValueConfig, obj.Config)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitFormDetectionRunsCreateRequest(t *testing.T) {
	t.Run("SetFile_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &FormDetectionRunsCreateRequest{}
		var fernTestValueFile *FormDetectionRunsCreateRequestFile

		// Act
		obj.SetFile(fernTestValueFile)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetConfig_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &FormDetectionRunsCreateRequest{}
		var fernTestValueConfig *EditSchemaGenerationConfig

		// Act
		obj.SetConfig(fernTestValueConfig)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersFormDetectionRunsRetrieveRequest(t *testing.T) {
	t.Run("SetExtendWorkspaceID", func(t *testing.T) {
		obj := &FormDetectionRunsRetrieveRequest{}
		var fernTestValueExtendWorkspaceID *string
		obj.SetExtendWorkspaceID(fernTestValueExtendWorkspaceID)
		assert.Equal(t, fernTestValueExtendWorkspaceID, obj.ExtendWorkspaceID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitFormDetectionRunsRetrieveRequest(t *testing.T) {
	t.Run("SetExtendWorkspaceID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &FormDetectionRunsRetrieveRequest{}
		var fernTestValueExtendWorkspaceID *string

		// Act
		obj.SetExtendWorkspaceID(fernTestValueExtendWorkspaceID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestGettersFormDetectionRunsCreateRequestFile(t *testing.T) {
	t.Run("GetFileFromURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &FormDetectionRunsCreateRequestFile{}
		var expected *FileFromURL
		obj.FileFromURL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetFileFromURL(), "getter should return the property value")
	})

	t.Run("GetFileFromURL_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &FormDetectionRunsCreateRequestFile{}
		obj.FileFromURL = nil

		// Act & Assert
		assert.Nil(t, obj.GetFileFromURL(), "getter should return nil when property is nil")
	})

	t.Run("GetFileFromURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *FormDetectionRunsCreateRequestFile
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetFileFromURL() // Should return zero value
	})

	t.Run("GetFileFromID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &FormDetectionRunsCreateRequestFile{}
		var expected *FileFromID
		obj.FileFromID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetFileFromID(), "getter should return the property value")
	})

	t.Run("GetFileFromID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &FormDetectionRunsCreateRequestFile{}
		obj.FileFromID = nil

		// Act & Assert
		assert.Nil(t, obj.GetFileFromID(), "getter should return nil when property is nil")
	})

	t.Run("GetFileFromID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *FormDetectionRunsCreateRequestFile
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetFileFromID() // Should return zero value
	})

}
