// Code generated by Fern. DO NOT EDIT.

package extend

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/extend-hq/extend-go-sdk/internal"
	big "math/big"
)

var (
	processorVersionCreateRequestFieldExtendWorkspaceID = big.NewInt(1 << 0)
	processorVersionCreateRequestFieldReleaseType       = big.NewInt(1 << 1)
	processorVersionCreateRequestFieldDescription       = big.NewInt(1 << 2)
	processorVersionCreateRequestFieldConfig            = big.NewInt(1 << 3)
)

type ProcessorVersionCreateRequest struct {
	// The workspace ID to target. **Required** when using an organization-scoped API key; optional for workspace-scoped keys (the key is already tied to a workspace). See [Authentication](https://docs.extend.ai/2026-02-09/developers/authentication) for details on API key scopes.
	ExtendWorkspaceID *string `json:"-" url:"-"`
	// The type of release for this version. The two options are "major" and "minor", which will increment the version number accordingly.
	ReleaseType ProcessorVersionCreateRequestReleaseType `json:"releaseType" url:"-"`
	// A description of the changes in this version. This helps track the evolution of the processor over time.
	Description *string `json:"description,omitempty" url:"-"`
	// The configuration for this version of the processor. The type of configuration must match the processor type.
	Config *ProcessorVersionCreateRequestConfig `json:"config,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *ProcessorVersionCreateRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetExtendWorkspaceID sets the ExtendWorkspaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProcessorVersionCreateRequest) SetExtendWorkspaceID(extendWorkspaceID *string) {
	p.ExtendWorkspaceID = extendWorkspaceID
	p.require(processorVersionCreateRequestFieldExtendWorkspaceID)
}

// SetReleaseType sets the ReleaseType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProcessorVersionCreateRequest) SetReleaseType(releaseType ProcessorVersionCreateRequestReleaseType) {
	p.ReleaseType = releaseType
	p.require(processorVersionCreateRequestFieldReleaseType)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProcessorVersionCreateRequest) SetDescription(description *string) {
	p.Description = description
	p.require(processorVersionCreateRequestFieldDescription)
}

// SetConfig sets the Config field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProcessorVersionCreateRequest) SetConfig(config *ProcessorVersionCreateRequestConfig) {
	p.Config = config
	p.require(processorVersionCreateRequestFieldConfig)
}

func (p *ProcessorVersionCreateRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler ProcessorVersionCreateRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*p = ProcessorVersionCreateRequest(body)
	return nil
}

func (p *ProcessorVersionCreateRequest) MarshalJSON() ([]byte, error) {
	type embed ProcessorVersionCreateRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	processorVersionGetRequestFieldExtendWorkspaceID = big.NewInt(1 << 0)
)

type ProcessorVersionGetRequest struct {
	// The workspace ID to target. **Required** when using an organization-scoped API key; optional for workspace-scoped keys (the key is already tied to a workspace). See [Authentication](https://docs.extend.ai/2026-02-09/developers/authentication) for details on API key scopes.
	ExtendWorkspaceID *string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *ProcessorVersionGetRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetExtendWorkspaceID sets the ExtendWorkspaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProcessorVersionGetRequest) SetExtendWorkspaceID(extendWorkspaceID *string) {
	p.ExtendWorkspaceID = extendWorkspaceID
	p.require(processorVersionGetRequestFieldExtendWorkspaceID)
}

var (
	processorVersionListRequestFieldExtendWorkspaceID = big.NewInt(1 << 0)
)

type ProcessorVersionListRequest struct {
	// The workspace ID to target. **Required** when using an organization-scoped API key; optional for workspace-scoped keys (the key is already tied to a workspace). See [Authentication](https://docs.extend.ai/2026-02-09/developers/authentication) for details on API key scopes.
	ExtendWorkspaceID *string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *ProcessorVersionListRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetExtendWorkspaceID sets the ExtendWorkspaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProcessorVersionListRequest) SetExtendWorkspaceID(extendWorkspaceID *string) {
	p.ExtendWorkspaceID = extendWorkspaceID
	p.require(processorVersionListRequestFieldExtendWorkspaceID)
}

// The configuration for this version of the processor. The type of configuration must match the processor type.
type ProcessorVersionCreateRequestConfig struct {
	Type     string
	Classify *LegacyClassificationConfig
	Extract  *LegacyExtractionConfig
	Splitter *LegacySplitterConfig
}

func (p *ProcessorVersionCreateRequestConfig) GetType() string {
	if p == nil {
		return ""
	}
	return p.Type
}

func (p *ProcessorVersionCreateRequestConfig) GetClassify() *LegacyClassificationConfig {
	if p == nil {
		return nil
	}
	return p.Classify
}

func (p *ProcessorVersionCreateRequestConfig) GetExtract() *LegacyExtractionConfig {
	if p == nil {
		return nil
	}
	return p.Extract
}

func (p *ProcessorVersionCreateRequestConfig) GetSplitter() *LegacySplitterConfig {
	if p == nil {
		return nil
	}
	return p.Splitter
}

func (p *ProcessorVersionCreateRequestConfig) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	p.Type = unmarshaler.Type
	if unmarshaler.Type == "" {
		return fmt.Errorf("%T did not include discriminant type", p)
	}
	switch unmarshaler.Type {
	case "CLASSIFY":
		value := new(LegacyClassificationConfig)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		p.Classify = value
	case "EXTRACT":
		value := new(LegacyExtractionConfig)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		p.Extract = value
	case "SPLITTER":
		value := new(LegacySplitterConfig)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		p.Splitter = value
	}
	return nil
}

func (p ProcessorVersionCreateRequestConfig) MarshalJSON() ([]byte, error) {
	if err := p.validate(); err != nil {
		return nil, err
	}
	if p.Classify != nil {
		return internal.MarshalJSONWithExtraProperty(p.Classify, "type", "CLASSIFY")
	}
	if p.Extract != nil {
		return internal.MarshalJSONWithExtraProperty(p.Extract, "type", "EXTRACT")
	}
	if p.Splitter != nil {
		return internal.MarshalJSONWithExtraProperty(p.Splitter, "type", "SPLITTER")
	}
	return nil, fmt.Errorf("type %T does not define a non-empty union type", p)
}

type ProcessorVersionCreateRequestConfigVisitor interface {
	VisitClassify(*LegacyClassificationConfig) error
	VisitExtract(*LegacyExtractionConfig) error
	VisitSplitter(*LegacySplitterConfig) error
}

func (p *ProcessorVersionCreateRequestConfig) Accept(visitor ProcessorVersionCreateRequestConfigVisitor) error {
	if p.Classify != nil {
		return visitor.VisitClassify(p.Classify)
	}
	if p.Extract != nil {
		return visitor.VisitExtract(p.Extract)
	}
	if p.Splitter != nil {
		return visitor.VisitSplitter(p.Splitter)
	}
	return fmt.Errorf("type %T does not define a non-empty union type", p)
}

func (p *ProcessorVersionCreateRequestConfig) validate() error {
	if p == nil {
		return fmt.Errorf("type %T is nil", p)
	}
	var fields []string
	if p.Classify != nil {
		fields = append(fields, "CLASSIFY")
	}
	if p.Extract != nil {
		fields = append(fields, "EXTRACT")
	}
	if p.Splitter != nil {
		fields = append(fields, "SPLITTER")
	}
	if len(fields) == 0 {
		if p.Type != "" {
			return fmt.Errorf("type %T defines a discriminant set to %q but the field is not set", p, p.Type)
		}
		return fmt.Errorf("type %T is empty", p)
	}
	if len(fields) > 1 {
		return fmt.Errorf("type %T defines values for %s, but only one value is allowed", p, fields)
	}
	if p.Type != "" {
		field := fields[0]
		if p.Type != field {
			return fmt.Errorf(
				"type %T defines a discriminant set to %q, but it does not match the %T field; either remove or update the discriminant to match",
				p,
				p.Type,
				p,
			)
		}
	}
	return nil
}

// The type of release for this version. The two options are "major" and "minor", which will increment the version number accordingly.
type ProcessorVersionCreateRequestReleaseType string

const (
	ProcessorVersionCreateRequestReleaseTypeMajor ProcessorVersionCreateRequestReleaseType = "major"
	ProcessorVersionCreateRequestReleaseTypeMinor ProcessorVersionCreateRequestReleaseType = "minor"
)

func NewProcessorVersionCreateRequestReleaseTypeFromString(s string) (ProcessorVersionCreateRequestReleaseType, error) {
	switch s {
	case "major":
		return ProcessorVersionCreateRequestReleaseTypeMajor, nil
	case "minor":
		return ProcessorVersionCreateRequestReleaseTypeMinor, nil
	}
	var t ProcessorVersionCreateRequestReleaseType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p ProcessorVersionCreateRequestReleaseType) Ptr() *ProcessorVersionCreateRequestReleaseType {
	return &p
}

var (
	processorVersionCreateResponseFieldSuccess          = big.NewInt(1 << 0)
	processorVersionCreateResponseFieldProcessorVersion = big.NewInt(1 << 1)
)

type ProcessorVersionCreateResponse struct {
	Success          bool                    `json:"success" url:"success"`
	ProcessorVersion *LegacyProcessorVersion `json:"processorVersion" url:"processorVersion"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *ProcessorVersionCreateResponse) GetSuccess() bool {
	if p == nil {
		return false
	}
	return p.Success
}

func (p *ProcessorVersionCreateResponse) GetProcessorVersion() *LegacyProcessorVersion {
	if p == nil {
		return nil
	}
	return p.ProcessorVersion
}

func (p *ProcessorVersionCreateResponse) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *ProcessorVersionCreateResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProcessorVersionCreateResponse) SetSuccess(success bool) {
	p.Success = success
	p.require(processorVersionCreateResponseFieldSuccess)
}

// SetProcessorVersion sets the ProcessorVersion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProcessorVersionCreateResponse) SetProcessorVersion(processorVersion *LegacyProcessorVersion) {
	p.ProcessorVersion = processorVersion
	p.require(processorVersionCreateResponseFieldProcessorVersion)
}

func (p *ProcessorVersionCreateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ProcessorVersionCreateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = ProcessorVersionCreateResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *ProcessorVersionCreateResponse) MarshalJSON() ([]byte, error) {
	type embed ProcessorVersionCreateResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *ProcessorVersionCreateResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	processorVersionGetResponseFieldSuccess = big.NewInt(1 << 0)
	processorVersionGetResponseFieldVersion = big.NewInt(1 << 1)
)

type ProcessorVersionGetResponse struct {
	Success bool `json:"success" url:"success"`
	// A ProcessorVersion object representing the requested version of the processor.
	Version *LegacyProcessorVersion `json:"version" url:"version"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *ProcessorVersionGetResponse) GetSuccess() bool {
	if p == nil {
		return false
	}
	return p.Success
}

func (p *ProcessorVersionGetResponse) GetVersion() *LegacyProcessorVersion {
	if p == nil {
		return nil
	}
	return p.Version
}

func (p *ProcessorVersionGetResponse) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *ProcessorVersionGetResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProcessorVersionGetResponse) SetSuccess(success bool) {
	p.Success = success
	p.require(processorVersionGetResponseFieldSuccess)
}

// SetVersion sets the Version field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProcessorVersionGetResponse) SetVersion(version *LegacyProcessorVersion) {
	p.Version = version
	p.require(processorVersionGetResponseFieldVersion)
}

func (p *ProcessorVersionGetResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ProcessorVersionGetResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = ProcessorVersionGetResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *ProcessorVersionGetResponse) MarshalJSON() ([]byte, error) {
	type embed ProcessorVersionGetResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *ProcessorVersionGetResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	processorVersionListResponseFieldSuccess  = big.NewInt(1 << 0)
	processorVersionListResponseFieldVersions = big.NewInt(1 << 1)
)

type ProcessorVersionListResponse struct {
	Success bool `json:"success" url:"success"`
	// An array of ProcessorVersion objects representing all versions of the specified processor.
	Versions []*LegacyProcessorVersion `json:"versions" url:"versions"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *ProcessorVersionListResponse) GetSuccess() bool {
	if p == nil {
		return false
	}
	return p.Success
}

func (p *ProcessorVersionListResponse) GetVersions() []*LegacyProcessorVersion {
	if p == nil {
		return nil
	}
	return p.Versions
}

func (p *ProcessorVersionListResponse) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *ProcessorVersionListResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProcessorVersionListResponse) SetSuccess(success bool) {
	p.Success = success
	p.require(processorVersionListResponseFieldSuccess)
}

// SetVersions sets the Versions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *ProcessorVersionListResponse) SetVersions(versions []*LegacyProcessorVersion) {
	p.Versions = versions
	p.require(processorVersionListResponseFieldVersions)
}

func (p *ProcessorVersionListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ProcessorVersionListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = ProcessorVersionListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *ProcessorVersionListResponse) MarshalJSON() ([]byte, error) {
	type embed ProcessorVersionListResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *ProcessorVersionListResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}
