// Code generated by Fern. DO NOT EDIT.

package extend

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
	time "time"
)

func TestSettersWebhookSubscriptionsCreateRequest(t *testing.T) {
	t.Run("SetWebhookEndpointID", func(t *testing.T) {
		obj := &WebhookSubscriptionsCreateRequest{}
		var fernTestValueWebhookEndpointID string
		obj.SetWebhookEndpointID(fernTestValueWebhookEndpointID)
		assert.Equal(t, fernTestValueWebhookEndpointID, obj.WebhookEndpointID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetResourceType", func(t *testing.T) {
		obj := &WebhookSubscriptionsCreateRequest{}
		var fernTestValueResourceType WebhookSubscriptionResourceType
		obj.SetResourceType(fernTestValueResourceType)
		assert.Equal(t, fernTestValueResourceType, obj.ResourceType)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetResourceID", func(t *testing.T) {
		obj := &WebhookSubscriptionsCreateRequest{}
		var fernTestValueResourceID string
		obj.SetResourceID(fernTestValueResourceID)
		assert.Equal(t, fernTestValueResourceID, obj.ResourceID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEnabledEvents", func(t *testing.T) {
		obj := &WebhookSubscriptionsCreateRequest{}
		var fernTestValueEnabledEvents []WebhookSubscriptionEventType
		obj.SetEnabledEvents(fernTestValueEnabledEvents)
		assert.Equal(t, fernTestValueEnabledEvents, obj.EnabledEvents)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitWebhookSubscriptionsCreateRequest(t *testing.T) {
	t.Run("SetWebhookEndpointID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscriptionsCreateRequest{}
		var fernTestValueWebhookEndpointID string

		// Act
		obj.SetWebhookEndpointID(fernTestValueWebhookEndpointID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetResourceType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscriptionsCreateRequest{}
		var fernTestValueResourceType WebhookSubscriptionResourceType

		// Act
		obj.SetResourceType(fernTestValueResourceType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetResourceID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscriptionsCreateRequest{}
		var fernTestValueResourceID string

		// Act
		obj.SetResourceID(fernTestValueResourceID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEnabledEvents_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscriptionsCreateRequest{}
		var fernTestValueEnabledEvents []WebhookSubscriptionEventType

		// Act
		obj.SetEnabledEvents(fernTestValueEnabledEvents)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersWebhookSubscriptionsDeleteRequest(t *testing.T) {
	t.Run("SetExtendWorkspaceID", func(t *testing.T) {
		obj := &WebhookSubscriptionsDeleteRequest{}
		var fernTestValueExtendWorkspaceID *string
		obj.SetExtendWorkspaceID(fernTestValueExtendWorkspaceID)
		assert.Equal(t, fernTestValueExtendWorkspaceID, obj.ExtendWorkspaceID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitWebhookSubscriptionsDeleteRequest(t *testing.T) {
	t.Run("SetExtendWorkspaceID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscriptionsDeleteRequest{}
		var fernTestValueExtendWorkspaceID *string

		// Act
		obj.SetExtendWorkspaceID(fernTestValueExtendWorkspaceID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersWebhookSubscriptionsListRequest(t *testing.T) {
	t.Run("SetExtendWorkspaceID", func(t *testing.T) {
		obj := &WebhookSubscriptionsListRequest{}
		var fernTestValueExtendWorkspaceID *string
		obj.SetExtendWorkspaceID(fernTestValueExtendWorkspaceID)
		assert.Equal(t, fernTestValueExtendWorkspaceID, obj.ExtendWorkspaceID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWebhookEndpointID", func(t *testing.T) {
		obj := &WebhookSubscriptionsListRequest{}
		var fernTestValueWebhookEndpointID *string
		obj.SetWebhookEndpointID(fernTestValueWebhookEndpointID)
		assert.Equal(t, fernTestValueWebhookEndpointID, obj.WebhookEndpointID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetResourceID", func(t *testing.T) {
		obj := &WebhookSubscriptionsListRequest{}
		var fernTestValueResourceID *string
		obj.SetResourceID(fernTestValueResourceID)
		assert.Equal(t, fernTestValueResourceID, obj.ResourceID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSortDir", func(t *testing.T) {
		obj := &WebhookSubscriptionsListRequest{}
		var fernTestValueSortDir *SortDir
		obj.SetSortDir(fernTestValueSortDir)
		assert.Equal(t, fernTestValueSortDir, obj.SortDir)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetNextPageToken", func(t *testing.T) {
		obj := &WebhookSubscriptionsListRequest{}
		var fernTestValueNextPageToken *NextPageToken
		obj.SetNextPageToken(fernTestValueNextPageToken)
		assert.Equal(t, fernTestValueNextPageToken, obj.NextPageToken)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMaxPageSize", func(t *testing.T) {
		obj := &WebhookSubscriptionsListRequest{}
		var fernTestValueMaxPageSize *MaxPageSize
		obj.SetMaxPageSize(fernTestValueMaxPageSize)
		assert.Equal(t, fernTestValueMaxPageSize, obj.MaxPageSize)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitWebhookSubscriptionsListRequest(t *testing.T) {
	t.Run("SetExtendWorkspaceID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscriptionsListRequest{}
		var fernTestValueExtendWorkspaceID *string

		// Act
		obj.SetExtendWorkspaceID(fernTestValueExtendWorkspaceID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWebhookEndpointID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscriptionsListRequest{}
		var fernTestValueWebhookEndpointID *string

		// Act
		obj.SetWebhookEndpointID(fernTestValueWebhookEndpointID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetResourceID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscriptionsListRequest{}
		var fernTestValueResourceID *string

		// Act
		obj.SetResourceID(fernTestValueResourceID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSortDir_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscriptionsListRequest{}
		var fernTestValueSortDir *SortDir

		// Act
		obj.SetSortDir(fernTestValueSortDir)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetNextPageToken_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscriptionsListRequest{}
		var fernTestValueNextPageToken *NextPageToken

		// Act
		obj.SetNextPageToken(fernTestValueNextPageToken)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMaxPageSize_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscriptionsListRequest{}
		var fernTestValueMaxPageSize *MaxPageSize

		// Act
		obj.SetMaxPageSize(fernTestValueMaxPageSize)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersWebhookSubscriptionsRetrieveRequest(t *testing.T) {
	t.Run("SetExtendWorkspaceID", func(t *testing.T) {
		obj := &WebhookSubscriptionsRetrieveRequest{}
		var fernTestValueExtendWorkspaceID *string
		obj.SetExtendWorkspaceID(fernTestValueExtendWorkspaceID)
		assert.Equal(t, fernTestValueExtendWorkspaceID, obj.ExtendWorkspaceID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitWebhookSubscriptionsRetrieveRequest(t *testing.T) {
	t.Run("SetExtendWorkspaceID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscriptionsRetrieveRequest{}
		var fernTestValueExtendWorkspaceID *string

		// Act
		obj.SetExtendWorkspaceID(fernTestValueExtendWorkspaceID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersWebhookSubscription(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &WebhookSubscription{}
		var fernTestValueID string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWebhookEndpointID", func(t *testing.T) {
		obj := &WebhookSubscription{}
		var fernTestValueWebhookEndpointID string
		obj.SetWebhookEndpointID(fernTestValueWebhookEndpointID)
		assert.Equal(t, fernTestValueWebhookEndpointID, obj.WebhookEndpointID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetResourceType", func(t *testing.T) {
		obj := &WebhookSubscription{}
		var fernTestValueResourceType WebhookSubscriptionResourceType
		obj.SetResourceType(fernTestValueResourceType)
		assert.Equal(t, fernTestValueResourceType, obj.ResourceType)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetResourceID", func(t *testing.T) {
		obj := &WebhookSubscription{}
		var fernTestValueResourceID string
		obj.SetResourceID(fernTestValueResourceID)
		assert.Equal(t, fernTestValueResourceID, obj.ResourceID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEnabledEvents", func(t *testing.T) {
		obj := &WebhookSubscription{}
		var fernTestValueEnabledEvents []WebhookSubscriptionEventType
		obj.SetEnabledEvents(fernTestValueEnabledEvents)
		assert.Equal(t, fernTestValueEnabledEvents, obj.EnabledEvents)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedAt", func(t *testing.T) {
		obj := &WebhookSubscription{}
		var fernTestValueCreatedAt time.Time
		obj.SetCreatedAt(fernTestValueCreatedAt)
		assert.Equal(t, fernTestValueCreatedAt, obj.CreatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersWebhookSubscription(t *testing.T) {
	t.Run("GetID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscription{}
		var expected string
		obj.ID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetID(), "getter should return the property value")
	})

	t.Run("GetID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookSubscription
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetID() // Should return zero value
	})

	t.Run("GetWebhookEndpointID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscription{}
		var expected string
		obj.WebhookEndpointID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetWebhookEndpointID(), "getter should return the property value")
	})

	t.Run("GetWebhookEndpointID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookSubscription
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetWebhookEndpointID() // Should return zero value
	})

	t.Run("GetResourceType", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscription{}
		var expected WebhookSubscriptionResourceType
		obj.ResourceType = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetResourceType(), "getter should return the property value")
	})

	t.Run("GetResourceType_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookSubscription
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetResourceType() // Should return zero value
	})

	t.Run("GetResourceID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscription{}
		var expected string
		obj.ResourceID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetResourceID(), "getter should return the property value")
	})

	t.Run("GetResourceID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookSubscription
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetResourceID() // Should return zero value
	})

	t.Run("GetEnabledEvents", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscription{}
		var expected []WebhookSubscriptionEventType
		obj.EnabledEvents = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEnabledEvents(), "getter should return the property value")
	})

	t.Run("GetEnabledEvents_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscription{}
		obj.EnabledEvents = nil

		// Act & Assert
		assert.Nil(t, obj.GetEnabledEvents(), "getter should return nil when property is nil")
	})

	t.Run("GetEnabledEvents_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookSubscription
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEnabledEvents() // Should return zero value
	})

	t.Run("GetCreatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscription{}
		var expected time.Time
		obj.CreatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCreatedAt(), "getter should return the property value")
	})

	t.Run("GetCreatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookSubscription
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCreatedAt() // Should return zero value
	})

}

func TestSettersMarkExplicitWebhookSubscription(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscription{}
		var fernTestValueID string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWebhookEndpointID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscription{}
		var fernTestValueWebhookEndpointID string

		// Act
		obj.SetWebhookEndpointID(fernTestValueWebhookEndpointID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetResourceType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscription{}
		var fernTestValueResourceType WebhookSubscriptionResourceType

		// Act
		obj.SetResourceType(fernTestValueResourceType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetResourceID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscription{}
		var fernTestValueResourceID string

		// Act
		obj.SetResourceID(fernTestValueResourceID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEnabledEvents_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscription{}
		var fernTestValueEnabledEvents []WebhookSubscriptionEventType

		// Act
		obj.SetEnabledEvents(fernTestValueEnabledEvents)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscription{}
		var fernTestValueCreatedAt time.Time

		// Act
		obj.SetCreatedAt(fernTestValueCreatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersWebhookSubscriptionsDeleteResponse(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &WebhookSubscriptionsDeleteResponse{}
		var fernTestValueID string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersWebhookSubscriptionsDeleteResponse(t *testing.T) {
	t.Run("GetID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscriptionsDeleteResponse{}
		var expected string
		obj.ID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetID(), "getter should return the property value")
	})

	t.Run("GetID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookSubscriptionsDeleteResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetID() // Should return zero value
	})

}

func TestSettersMarkExplicitWebhookSubscriptionsDeleteResponse(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscriptionsDeleteResponse{}
		var fernTestValueID string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersWebhookSubscriptionsListResponse(t *testing.T) {
	t.Run("SetData", func(t *testing.T) {
		obj := &WebhookSubscriptionsListResponse{}
		var fernTestValueData []*WebhookSubscription
		obj.SetData(fernTestValueData)
		assert.Equal(t, fernTestValueData, obj.Data)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetNextPageToken", func(t *testing.T) {
		obj := &WebhookSubscriptionsListResponse{}
		var fernTestValueNextPageToken *NextPageToken
		obj.SetNextPageToken(fernTestValueNextPageToken)
		assert.Equal(t, fernTestValueNextPageToken, obj.NextPageToken)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersWebhookSubscriptionsListResponse(t *testing.T) {
	t.Run("GetData", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscriptionsListResponse{}
		var expected []*WebhookSubscription
		obj.Data = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetData(), "getter should return the property value")
	})

	t.Run("GetData_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscriptionsListResponse{}
		obj.Data = nil

		// Act & Assert
		assert.Nil(t, obj.GetData(), "getter should return nil when property is nil")
	})

	t.Run("GetData_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookSubscriptionsListResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetData() // Should return zero value
	})

	t.Run("GetNextPageToken", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscriptionsListResponse{}
		var expected *NextPageToken
		obj.NextPageToken = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetNextPageToken(), "getter should return the property value")
	})

	t.Run("GetNextPageToken_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscriptionsListResponse{}
		obj.NextPageToken = nil

		// Act & Assert
		assert.Nil(t, obj.GetNextPageToken(), "getter should return nil when property is nil")
	})

	t.Run("GetNextPageToken_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookSubscriptionsListResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetNextPageToken() // Should return zero value
	})

}

func TestSettersMarkExplicitWebhookSubscriptionsListResponse(t *testing.T) {
	t.Run("SetData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscriptionsListResponse{}
		var fernTestValueData []*WebhookSubscription

		// Act
		obj.SetData(fernTestValueData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetNextPageToken_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscriptionsListResponse{}
		var fernTestValueNextPageToken *NextPageToken

		// Act
		obj.SetNextPageToken(fernTestValueNextPageToken)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersWebhookSubscriptionsUpdateRequest(t *testing.T) {
	t.Run("SetExtendWorkspaceID", func(t *testing.T) {
		obj := &WebhookSubscriptionsUpdateRequest{}
		var fernTestValueExtendWorkspaceID *string
		obj.SetExtendWorkspaceID(fernTestValueExtendWorkspaceID)
		assert.Equal(t, fernTestValueExtendWorkspaceID, obj.ExtendWorkspaceID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEnabledEvents", func(t *testing.T) {
		obj := &WebhookSubscriptionsUpdateRequest{}
		var fernTestValueEnabledEvents []WebhookSubscriptionEventType
		obj.SetEnabledEvents(fernTestValueEnabledEvents)
		assert.Equal(t, fernTestValueEnabledEvents, obj.EnabledEvents)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitWebhookSubscriptionsUpdateRequest(t *testing.T) {
	t.Run("SetExtendWorkspaceID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscriptionsUpdateRequest{}
		var fernTestValueExtendWorkspaceID *string

		// Act
		obj.SetExtendWorkspaceID(fernTestValueExtendWorkspaceID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEnabledEvents_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscriptionsUpdateRequest{}
		var fernTestValueEnabledEvents []WebhookSubscriptionEventType

		// Act
		obj.SetEnabledEvents(fernTestValueEnabledEvents)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingWebhookSubscription(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscription{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled WebhookSubscription
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj WebhookSubscription
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

}

func TestJSONMarshalingWebhookSubscriptionsDeleteResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscriptionsDeleteResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled WebhookSubscriptionsDeleteResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj WebhookSubscriptionsDeleteResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj WebhookSubscriptionsDeleteResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingWebhookSubscriptionsListResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookSubscriptionsListResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled WebhookSubscriptionsListResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj WebhookSubscriptionsListResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

}

func TestStringWebhookSubscription(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &WebhookSubscription{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookSubscription
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringWebhookSubscriptionsDeleteResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &WebhookSubscriptionsDeleteResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookSubscriptionsDeleteResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringWebhookSubscriptionsListResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &WebhookSubscriptionsListResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookSubscriptionsListResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumWebhookSubscriptionEventType(t *testing.T) {
	t.Run("NewFromString_extract_run_processed", func(t *testing.T) {
		t.Parallel()
		val, err := NewWebhookSubscriptionEventTypeFromString("extract_run.processed")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, WebhookSubscriptionEventType("extract_run.processed"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_extract_run_failed", func(t *testing.T) {
		t.Parallel()
		val, err := NewWebhookSubscriptionEventTypeFromString("extract_run.failed")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, WebhookSubscriptionEventType("extract_run.failed"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_classify_run_processed", func(t *testing.T) {
		t.Parallel()
		val, err := NewWebhookSubscriptionEventTypeFromString("classify_run.processed")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, WebhookSubscriptionEventType("classify_run.processed"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_classify_run_failed", func(t *testing.T) {
		t.Parallel()
		val, err := NewWebhookSubscriptionEventTypeFromString("classify_run.failed")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, WebhookSubscriptionEventType("classify_run.failed"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_split_run_processed", func(t *testing.T) {
		t.Parallel()
		val, err := NewWebhookSubscriptionEventTypeFromString("split_run.processed")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, WebhookSubscriptionEventType("split_run.processed"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_split_run_failed", func(t *testing.T) {
		t.Parallel()
		val, err := NewWebhookSubscriptionEventTypeFromString("split_run.failed")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, WebhookSubscriptionEventType("split_run.failed"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_batch_processor_run_processed", func(t *testing.T) {
		t.Parallel()
		val, err := NewWebhookSubscriptionEventTypeFromString("batch_processor_run.processed")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, WebhookSubscriptionEventType("batch_processor_run.processed"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_batch_processor_run_failed", func(t *testing.T) {
		t.Parallel()
		val, err := NewWebhookSubscriptionEventTypeFromString("batch_processor_run.failed")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, WebhookSubscriptionEventType("batch_processor_run.failed"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_workflow_run_completed", func(t *testing.T) {
		t.Parallel()
		val, err := NewWebhookSubscriptionEventTypeFromString("workflow_run.completed")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, WebhookSubscriptionEventType("workflow_run.completed"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_workflow_run_failed", func(t *testing.T) {
		t.Parallel()
		val, err := NewWebhookSubscriptionEventTypeFromString("workflow_run.failed")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, WebhookSubscriptionEventType("workflow_run.failed"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_workflow_run_needs_review", func(t *testing.T) {
		t.Parallel()
		val, err := NewWebhookSubscriptionEventTypeFromString("workflow_run.needs_review")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, WebhookSubscriptionEventType("workflow_run.needs_review"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_workflow_run_rejected", func(t *testing.T) {
		t.Parallel()
		val, err := NewWebhookSubscriptionEventTypeFromString("workflow_run.rejected")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, WebhookSubscriptionEventType("workflow_run.rejected"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_workflow_run_cancelled", func(t *testing.T) {
		t.Parallel()
		val, err := NewWebhookSubscriptionEventTypeFromString("workflow_run.cancelled")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, WebhookSubscriptionEventType("workflow_run.cancelled"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_workflow_run_step_run_processed", func(t *testing.T) {
		t.Parallel()
		val, err := NewWebhookSubscriptionEventTypeFromString("workflow_run.step_run.processed")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, WebhookSubscriptionEventType("workflow_run.step_run.processed"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewWebhookSubscriptionEventTypeFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewWebhookSubscriptionEventTypeFromString("extract_run.processed")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumWebhookSubscriptionResourceType(t *testing.T) {
	t.Run("NewFromString_extractor", func(t *testing.T) {
		t.Parallel()
		val, err := NewWebhookSubscriptionResourceTypeFromString("extractor")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, WebhookSubscriptionResourceType("extractor"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_classifier", func(t *testing.T) {
		t.Parallel()
		val, err := NewWebhookSubscriptionResourceTypeFromString("classifier")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, WebhookSubscriptionResourceType("classifier"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_splitter", func(t *testing.T) {
		t.Parallel()
		val, err := NewWebhookSubscriptionResourceTypeFromString("splitter")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, WebhookSubscriptionResourceType("splitter"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_workflow", func(t *testing.T) {
		t.Parallel()
		val, err := NewWebhookSubscriptionResourceTypeFromString("workflow")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, WebhookSubscriptionResourceType("workflow"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewWebhookSubscriptionResourceTypeFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewWebhookSubscriptionResourceTypeFromString("extractor")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesWebhookSubscription(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &WebhookSubscription{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookSubscription
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesWebhookSubscriptionsDeleteResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &WebhookSubscriptionsDeleteResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookSubscriptionsDeleteResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesWebhookSubscriptionsListResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &WebhookSubscriptionsListResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookSubscriptionsListResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
