// Code generated by Fern. DO NOT EDIT.

package extend

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/extend-hq/extend-go-sdk/internal"
	big "math/big"
	time "time"
)

var (
	workflowsCreateRequestFieldName  = big.NewInt(1 << 0)
	workflowsCreateRequestFieldSteps = big.NewInt(1 << 1)
)

type WorkflowsCreateRequest struct {
	// The name of the workflow.
	Name string `json:"name" url:"-"`
	// The steps that define the workflow's processing graph. Each step has a `type`, a unique `name`, and optional `next` entries that define routing to downstream steps.
	//
	// When omitted, the workflow is created with default steps (`TRIGGER` → `PARSE`). The default steps may change in the future.
	//
	// See the [Configuring Workflows via API guide](https://docs.extend.ai/2026-02-09/product/workflows/configuring-workflows-via-api) for step definitions, branching patterns, and examples.
	Steps []*WorkflowStepDefinition `json:"steps,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (w *WorkflowsCreateRequest) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowsCreateRequest) SetName(name string) {
	w.Name = name
	w.require(workflowsCreateRequestFieldName)
}

// SetSteps sets the Steps field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowsCreateRequest) SetSteps(steps []*WorkflowStepDefinition) {
	w.Steps = steps
	w.require(workflowsCreateRequestFieldSteps)
}

func (w *WorkflowsCreateRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler WorkflowsCreateRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*w = WorkflowsCreateRequest(body)
	return nil
}

func (w *WorkflowsCreateRequest) MarshalJSON() ([]byte, error) {
	type embed WorkflowsCreateRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	workflowsListRequestFieldNextPageToken = big.NewInt(1 << 0)
	workflowsListRequestFieldMaxPageSize   = big.NewInt(1 << 1)
	workflowsListRequestFieldSortBy        = big.NewInt(1 << 2)
	workflowsListRequestFieldSortDir       = big.NewInt(1 << 3)
)

type WorkflowsListRequest struct {
	NextPageToken *NextPageToken `json:"-" url:"nextPageToken,omitempty"`
	MaxPageSize   *MaxPageSize   `json:"-" url:"maxPageSize,omitempty"`
	SortBy        *SortBy        `json:"-" url:"sortBy,omitempty"`
	SortDir       *SortDir       `json:"-" url:"sortDir,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (w *WorkflowsListRequest) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetNextPageToken sets the NextPageToken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowsListRequest) SetNextPageToken(nextPageToken *NextPageToken) {
	w.NextPageToken = nextPageToken
	w.require(workflowsListRequestFieldNextPageToken)
}

// SetMaxPageSize sets the MaxPageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowsListRequest) SetMaxPageSize(maxPageSize *MaxPageSize) {
	w.MaxPageSize = maxPageSize
	w.require(workflowsListRequestFieldMaxPageSize)
}

// SetSortBy sets the SortBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowsListRequest) SetSortBy(sortBy *SortBy) {
	w.SortBy = sortBy
	w.require(workflowsListRequestFieldSortBy)
}

// SetSortDir sets the SortDir field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowsListRequest) SetSortDir(sortDir *SortDir) {
	w.SortDir = sortDir
	w.require(workflowsListRequestFieldSortDir)
}

// A workflow with its draft version and steps.
var (
	workflowFieldID           = big.NewInt(1 << 0)
	workflowFieldName         = big.NewInt(1 << 1)
	workflowFieldCreatedAt    = big.NewInt(1 << 2)
	workflowFieldUpdatedAt    = big.NewInt(1 << 3)
	workflowFieldDraftVersion = big.NewInt(1 << 4)
)

type Workflow struct {
	// The ID of the workflow.
	ID string `json:"id" url:"id"`
	// The name of the workflow.
	Name         string           `json:"name" url:"name"`
	CreatedAt    CreatedAt        `json:"createdAt" url:"createdAt"`
	UpdatedAt    UpdatedAt        `json:"updatedAt" url:"updatedAt"`
	DraftVersion *WorkflowVersion `json:"draftVersion" url:"draftVersion"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
	object         string

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *Workflow) GetID() string {
	if w == nil {
		return ""
	}
	return w.ID
}

func (w *Workflow) GetName() string {
	if w == nil {
		return ""
	}
	return w.Name
}

func (w *Workflow) GetCreatedAt() CreatedAt {
	if w == nil {
		return time.Time{}
	}
	return w.CreatedAt
}

func (w *Workflow) GetUpdatedAt() UpdatedAt {
	if w == nil {
		return time.Time{}
	}
	return w.UpdatedAt
}

func (w *Workflow) GetDraftVersion() *WorkflowVersion {
	if w == nil {
		return nil
	}
	return w.DraftVersion
}

func (w *Workflow) Object() string {
	return w.object
}

func (w *Workflow) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *Workflow) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *Workflow) SetID(id string) {
	w.ID = id
	w.require(workflowFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *Workflow) SetName(name string) {
	w.Name = name
	w.require(workflowFieldName)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *Workflow) SetCreatedAt(createdAt CreatedAt) {
	w.CreatedAt = createdAt
	w.require(workflowFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *Workflow) SetUpdatedAt(updatedAt UpdatedAt) {
	w.UpdatedAt = updatedAt
	w.require(workflowFieldUpdatedAt)
}

// SetDraftVersion sets the DraftVersion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *Workflow) SetDraftVersion(draftVersion *WorkflowVersion) {
	w.DraftVersion = draftVersion
	w.require(workflowFieldDraftVersion)
}

func (w *Workflow) UnmarshalJSON(data []byte) error {
	type embed Workflow
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
		Object    string             `json:"object"`
	}{
		embed: embed(*w),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*w = Workflow(unmarshaler.embed)
	w.CreatedAt = unmarshaler.CreatedAt.Time()
	w.UpdatedAt = unmarshaler.UpdatedAt.Time()
	if unmarshaler.Object != "workflow" {
		return fmt.Errorf("unexpected value for literal on type %T; expected %v got %v", w, "workflow", unmarshaler.Object)
	}
	w.object = unmarshaler.Object
	extraProperties, err := internal.ExtractExtraProperties(data, *w, "object")
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *Workflow) MarshalJSON() ([]byte, error) {
	type embed Workflow
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
		Object    string             `json:"object"`
	}{
		embed:     embed(*w),
		CreatedAt: internal.NewDateTime(w.CreatedAt),
		UpdatedAt: internal.NewDateTime(w.UpdatedAt),
		Object:    "workflow",
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *Workflow) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

var (
	workflowsListResponseFieldData          = big.NewInt(1 << 0)
	workflowsListResponseFieldNextPageToken = big.NewInt(1 << 1)
)

type WorkflowsListResponse struct {
	Data          []*WorkflowSummary `json:"data" url:"data"`
	NextPageToken *NextPageToken     `json:"nextPageToken,omitempty" url:"nextPageToken,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
	object         string

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WorkflowsListResponse) GetData() []*WorkflowSummary {
	if w == nil {
		return nil
	}
	return w.Data
}

func (w *WorkflowsListResponse) GetNextPageToken() *NextPageToken {
	if w == nil {
		return nil
	}
	return w.NextPageToken
}

func (w *WorkflowsListResponse) Object() string {
	return w.object
}

func (w *WorkflowsListResponse) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WorkflowsListResponse) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowsListResponse) SetData(data []*WorkflowSummary) {
	w.Data = data
	w.require(workflowsListResponseFieldData)
}

// SetNextPageToken sets the NextPageToken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowsListResponse) SetNextPageToken(nextPageToken *NextPageToken) {
	w.NextPageToken = nextPageToken
	w.require(workflowsListResponseFieldNextPageToken)
}

func (w *WorkflowsListResponse) UnmarshalJSON(data []byte) error {
	type embed WorkflowsListResponse
	var unmarshaler = struct {
		embed
		Object string `json:"object"`
	}{
		embed: embed(*w),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*w = WorkflowsListResponse(unmarshaler.embed)
	if unmarshaler.Object != "list" {
		return fmt.Errorf("unexpected value for literal on type %T; expected %v got %v", w, "list", unmarshaler.Object)
	}
	w.object = unmarshaler.Object
	extraProperties, err := internal.ExtractExtraProperties(data, *w, "object")
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WorkflowsListResponse) MarshalJSON() ([]byte, error) {
	type embed WorkflowsListResponse
	var marshaler = struct {
		embed
		Object string `json:"object"`
	}{
		embed:  embed(*w),
		Object: "list",
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WorkflowsListResponse) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

var (
	workflowsUpdateRequestFieldName  = big.NewInt(1 << 0)
	workflowsUpdateRequestFieldSteps = big.NewInt(1 << 1)
)

type WorkflowsUpdateRequest struct {
	// The new name for the workflow.
	Name *string `json:"name,omitempty" url:"-"`
	// The new step definitions for the draft version. Replaces all existing draft steps.
	//
	// See the [Configuring Workflows via API guide](https://docs.extend.ai/2026-02-09/product/workflows/configuring-workflows-via-api) for step definitions, branching patterns, and examples.
	Steps []*WorkflowStepDefinition `json:"steps,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (w *WorkflowsUpdateRequest) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowsUpdateRequest) SetName(name *string) {
	w.Name = name
	w.require(workflowsUpdateRequestFieldName)
}

// SetSteps sets the Steps field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowsUpdateRequest) SetSteps(steps []*WorkflowStepDefinition) {
	w.Steps = steps
	w.require(workflowsUpdateRequestFieldSteps)
}

func (w *WorkflowsUpdateRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler WorkflowsUpdateRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*w = WorkflowsUpdateRequest(body)
	return nil
}

func (w *WorkflowsUpdateRequest) MarshalJSON() ([]byte, error) {
	type embed WorkflowsUpdateRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}
