// Code generated by Fern. DO NOT EDIT.

package editruns

import (
	context "context"

	extend "github.com/extend-hq/extend-go-sdk"
	core "github.com/extend-hq/extend-go-sdk/core"
	internal "github.com/extend-hq/extend-go-sdk/internal"
	option "github.com/extend-hq/extend-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Edit and manipulate PDF documents by detecting and filling form fields.
//
// The Edit Runs endpoint allows you to convert and edit documents and get an edit run ID that can be used to check status and retrieve results with the Get Edit Run endpoint.
//
// The request returns immediately with a `PROCESSING` status. Use webhooks or poll the Get Edit Run endpoint for results.
func (c *Client) Create(
	ctx context.Context,
	request *extend.EditRunsCreateRequest,
	opts ...option.RequestOption,
) (*extend.EditRun, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve the status and results of an edit run.
//
// Use this endpoint to get results for an edit run that has already completed, or to check on the status of an edit run initiated via the [Create Edit Run](https://docs.extend.ai/2026-02-09/developers/api-reference/endpoints/edit/create-edit-run) endpoint.
func (c *Client) Retrieve(
	ctx context.Context,
	// The unique identifier for the edit run.
	//
	// Example: `"edr_xK9mLPqRtN3vS8wF5hB2cQ"`
	id string,
	request *extend.EditRunsRetrieveRequest,
	opts ...option.RequestOption,
) (*extend.EditRun, error) {
	response, err := c.WithRawResponse.Retrieve(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete an edit run and all associated data from Extend. This operation is permanent and cannot be undone.
//
// This endpoint can be used if you'd like to manage data retention on your own rather than relying on automated data retention policies, or to make one-off deletions for your downstream customers.
func (c *Client) Delete(
	ctx context.Context,
	// The ID of the edit run to delete.
	//
	// Example: `"edr_xK9mLPqRtN3vS8wF5hB2cQ"`
	id string,
	request *extend.EditRunsDeleteRequest,
	opts ...option.RequestOption,
) (*extend.EditRunsDeleteResponse, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
