// Code generated by Fern. DO NOT EDIT.

package workflowruns

import (
	context "context"

	extend "github.com/extend-hq/extend-go-sdk"
	core "github.com/extend-hq/extend-go-sdk/core"
	internal "github.com/extend-hq/extend-go-sdk/internal"
	option "github.com/extend-hq/extend-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// List runs of a Workflow. Workflows are sequences of steps that process files and data in a specific order to achieve a desired outcome. A WorkflowRun represents a single execution of a workflow against a file.
func (c *Client) List(
	ctx context.Context,
	request *extend.WorkflowRunsListRequest,
	opts ...option.RequestOption,
) (*extend.WorkflowRunsListResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Run a workflow with a file. A workflow is a sequence of steps that process files and data in a specific order to achieve a desired outcome.
//
// The request returns immediately with a `PROCESSING` status. Use webhooks or poll the Get Workflow Run endpoint for results.
func (c *Client) Create(
	ctx context.Context,
	request *extend.WorkflowRunsCreateRequest,
	opts ...option.RequestOption,
) (*extend.WorkflowRun, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Once a workflow has been run, you can check the status and output of a specific WorkflowRun.
func (c *Client) Retrieve(
	ctx context.Context,
	// The ID of the workflow run.
	//
	// Example: `"workflow_run_xKm9pNv3qWsY_jL2tR5Dh"`
	id string,
	request *extend.WorkflowRunsRetrieveRequest,
	opts ...option.RequestOption,
) (*extend.WorkflowRun, error) {
	response, err := c.WithRawResponse.Retrieve(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// You can update the name and metadata of an in progress WorkflowRun at any time using this endpoint.
func (c *Client) Update(
	ctx context.Context,
	// The ID of the workflow run.
	//
	// Example: `"workflow_run_xKm9pNv3qWsY_jL2tR5Dh"`
	id string,
	request *extend.WorkflowRunsUpdateRequest,
	opts ...option.RequestOption,
) (*extend.WorkflowRun, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete a workflow run and all associated data from Extend. This operation is permanent and cannot be undone.
//
// This endpoint can be used if you'd like to manage data retention on your own rather than automated data retention policies. Or make one-off deletions for your downstream customers.
func (c *Client) Delete(
	ctx context.Context,
	// The ID of the workflow run.
	//
	// Example: `"workflow_run_xKm9pNv3qWsY_jL2tR5Dh"`
	id string,
	request *extend.WorkflowRunsDeleteRequest,
	opts ...option.RequestOption,
) (*extend.WorkflowRunsDeleteResponse, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Cancel a running workflow run by its ID. This endpoint allows you to stop a workflow run that is currently in progress.
//
// Note: Only workflow runs with a status of `PROCESSING` or `PENDING` can be cancelled. Workflow runs that are completed, failed, in review, rejected, or already cancelled cannot be cancelled.
func (c *Client) Cancel(
	ctx context.Context,
	// The ID of the workflow run.
	//
	// Example: `"workflow_run_xKm9pNv3qWsY_jL2tR5Dh"`
	id string,
	request *extend.WorkflowRunsCancelRequest,
	opts ...option.RequestOption,
) (*extend.WorkflowRun, error) {
	response, err := c.WithRawResponse.Cancel(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// This endpoint allows you to efficiently initiate large batches of workflow runs in a single request (up to 1,000 in a single request, but you can queue up multiple batches in rapid succession). It accepts an array of inputs, each containing a file and metadata pair. The primary use case for this endpoint is for doing large bulk runs of >1000 files at a time that can process over the course of a few hours without needing to manage rate limits that would likely occur using the primary run endpoint.
//
// Unlike the single [Run Workflow](https://docs.extend.ai/2026-02-09/developers/api-reference/endpoints/workflow/create-workflow-run) endpoint which returns the details of the created workflow runs immediately, this batch endpoint returns a `batchId`.
//
// Our recommended usage pattern is to integrate with [Webhooks](https://docs.extend.ai/2026-02-09/product/webhooks/configuration) for consuming results, using the `metadata` and `batchId` to match up results to the original inputs in your downstream systems. However, you can integrate in a polling mechanism by using a combination of the [List Workflow Runs](https://docs.extend.ai/2026-02-09/developers/api-reference/endpoints/workflow/list-workflow-runs) endpoint to fetch all runs via a batch, and then [Get Workflow Run](https://docs.extend.ai/2026-02-09/developers/api-reference/endpoints/workflow/get-workflow-run) to fetch the full outputs each run.
//
// **Priority:** All workflow runs created through this batch endpoint are automatically assigned a priority of 90.
//
// **Processing and Monitoring:**
// Upon successful submission, the endpoint returns a `batchId`. The individual workflow runs are then queued for processing.
//
// - **Monitoring:** Track the progress and consume results of individual runs using [Webhooks](https://docs.extend.ai/2026-02-09/product/webhooks/configuration). Subscribe to events like `workflow_run.completed`, `workflow_run.failed`, etc. The webhook payload for these events will include the corresponding `batchId` and the `metadata` you provided for each input.
// - **Fetching Results:** You can also use the [List Workflow Runs](https://docs.extend.ai/2026-02-09/developers/api-reference/endpoints/workflow/list-workflow-runs) endpoint and filter using the `batchId` query param.
func (c *Client) CreateBatch(
	ctx context.Context,
	request *extend.WorkflowRunsCreateBatchRequest,
	opts ...option.RequestOption,
) (*extend.WorkflowRunsCreateBatchResponse, error) {
	response, err := c.WithRawResponse.CreateBatch(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
