// Code generated by Fern. DO NOT EDIT.

package split_runs_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	extend "github.com/extend-hq/extend-go-sdk"
	client "github.com/extend-hq/extend-go-sdk/client"
	option "github.com/extend-hq/extend-go-sdk/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestSplitRunsListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &extend.SplitRunsListRequest{
		NextPageToken: extend.String(
			"xK9mLPqRtN3vS8wF5hB2cQ==:zWvUxYjM4nKpL7aDgE9HbTcR2mAyX3/Q+CNkfBSw1dZ=",
		),
	}
	_, invocationErr := client.SplitRuns.List(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSplitRunsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSplitRunsListWithWireMock", "GET", "/split_runs", map[string]string{"nextPageToken": "xK9mLPqRtN3vS8wF5hB2cQ==:zWvUxYjM4nKpL7aDgE9HbTcR2mAyX3/Q+CNkfBSw1dZ="}, 1)
}

func TestSplitRunsCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &extend.SplitRunsCreateRequest{
		Splitter: &extend.SplitRunsCreateRequestSplitter{
			ID: "spl_1234567890",
		},
		File: &extend.SplitRunsCreateRequestFile{
			FileFromURL: &extend.FileFromURL{
				URL: "https://example.com/multi-document.pdf",
			},
		},
	}
	_, invocationErr := client.SplitRuns.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSplitRunsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSplitRunsCreateWithWireMock", "POST", "/split_runs", nil, 1)
}

func TestSplitRunsRetrieveWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &extend.SplitRunsRetrieveRequest{}
	_, invocationErr := client.SplitRuns.Retrieve(
		context.TODO(),
		"split_run_id_here",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSplitRunsRetrieveWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSplitRunsRetrieveWithWireMock", "GET", "/split_runs/split_run_id_here", nil, 1)
}

func TestSplitRunsDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &extend.SplitRunsDeleteRequest{}
	_, invocationErr := client.SplitRuns.Delete(
		context.TODO(),
		"id",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSplitRunsDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSplitRunsDeleteWithWireMock", "DELETE", "/split_runs/id", nil, 1)
}

func TestSplitRunsCancelWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &extend.SplitRunsCancelRequest{}
	_, invocationErr := client.SplitRuns.Cancel(
		context.TODO(),
		"split_run_id_here",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSplitRunsCancelWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSplitRunsCancelWithWireMock", "POST", "/split_runs/split_run_id_here/cancel", nil, 1)
}

func TestSplitRunsCreateBatchWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &extend.SplitRunsCreateBatchRequest{
		Splitter: &extend.SplitRunsCreateBatchRequestSplitter{
			ID: "spl_xK9mLPqRtN3vS8wF5hB2cQ",
		},
		Inputs: []*extend.SplitRunsCreateBatchRequestInputsItem{
			&extend.SplitRunsCreateBatchRequestInputsItem{
				File: &extend.SplitRunsCreateBatchRequestInputsItemFile{
					FileFromURL: &extend.FileFromURL{
						URL: "https://example.com/multi-doc1.pdf",
					},
				},
				Metadata: &extend.RunMetadata{
					"customerId": "cust_abc123",
				},
			},
			&extend.SplitRunsCreateBatchRequestInputsItem{
				File: &extend.SplitRunsCreateBatchRequestInputsItemFile{
					FileFromURL: &extend.FileFromURL{
						URL: "https://example.com/multi-doc2.pdf",
					},
				},
				Metadata: &extend.RunMetadata{
					"customerId": "cust_def456",
				},
			},
			&extend.SplitRunsCreateBatchRequestInputsItem{
				File: &extend.SplitRunsCreateBatchRequestInputsItemFile{
					FileFromURL: &extend.FileFromURL{
						URL: "https://example.com/multi-doc3.pdf",
					},
				},
				Metadata: &extend.RunMetadata{
					"customerId": "cust_ghi789",
				},
			},
		},
	}
	_, invocationErr := client.SplitRuns.CreateBatch(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSplitRunsCreateBatchWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSplitRunsCreateBatchWithWireMock", "POST", "/split_runs/batch", nil, 1)
}
