// Code generated by Fern. DO NOT EDIT.

package processor

import (
	context "context"
	http "net/http"

	extend "github.com/extend-hq/extend-go-sdk"
	core "github.com/extend-hq/extend-go-sdk/core"
	internal "github.com/extend-hq/extend-go-sdk/internal"
	option "github.com/extend-hq/extend-go-sdk/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) List(
	ctx context.Context,
	request *extend.ProcessorListRequest,
	opts ...option.RequestOption,
) (*core.Response[*extend.LegacyListProcessorsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.extend.ai",
	)
	endpointURL := baseURL + "/processors"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.ExtendWorkspaceID != nil {
		headers.Add("x-extend-workspace-id", *request.ExtendWorkspaceID)
	}

	var response *extend.LegacyListProcessorsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(extend.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*extend.LegacyListProcessorsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Create(
	ctx context.Context,
	request *extend.ProcessorCreateRequest,
	opts ...option.RequestOption,
) (*core.Response[*extend.ProcessorCreateResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.extend.ai",
	)
	endpointURL := baseURL + "/processors"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *extend.ProcessorCreateResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(extend.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*extend.ProcessorCreateResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Update(
	ctx context.Context,
	// The ID of the processor to update.
	//
	// Example: `"ex_Xj8mK2pL9nR4vT7qY5wZ"`
	id string,
	request *extend.ProcessorUpdateRequest,
	opts ...option.RequestOption,
) (*core.Response[*extend.ProcessorUpdateResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.extend.ai",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/processors/%v",
		id,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.ExtendWorkspaceID != nil {
		headers.Add("x-extend-workspace-id", *request.ExtendWorkspaceID)
	}
	headers.Add("Content-Type", "application/json")
	var response *extend.ProcessorUpdateResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(extend.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*extend.ProcessorUpdateResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
