// Code generated by Fern. DO NOT EDIT.

package batchprocessorrun

import (
	context "context"
	os "os"

	extend "github.com/extend-hq/extend-go-sdk"
	core "github.com/extend-hq/extend-go-sdk/core"
	internal "github.com/extend-hq/extend-go-sdk/internal"
	option "github.com/extend-hq/extend-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.Token == "" {
		options.Token = os.Getenv("EXTEND_API_KEY")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Retrieve details about a batch processor run, including evaluation runs.
//
// **Deprecated:** This endpoint is maintained for backwards compatibility only and will be replaced in a future API version. Use [Get Evaluation Set Run](https://docs.extend.ai/2026-02-09/api-reference/endpoints/evaluation/get-evaluation-set-run) for interacting with evaluation set runs.
func (c *Client) Get(
	ctx context.Context,
	// The unique identifier of the batch processor run to retrieve.
	//
	// Example: `"bpr_Xj8mK2pL9nR4vT7qY5wZ"`
	id string,
	request *extend.BatchProcessorRunGetRequest,
	opts ...option.RequestOption,
) (*extend.BatchProcessorRunGetResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
