// Code generated by Fern. DO NOT EDIT.

package splitters

import (
	context "context"

	extend "github.com/extend-hq/extend-go-sdk"
	core "github.com/extend-hq/extend-go-sdk/core"
	internal "github.com/extend-hq/extend-go-sdk/internal"
	option "github.com/extend-hq/extend-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// List all splitters.
//
// Returns a summary of each splitter. Use `GET /splitters/{id}` to retrieve the full object including `draftVersion`.
func (c *Client) List(
	ctx context.Context,
	request *extend.SplittersListRequest,
	opts ...option.RequestOption,
) (*extend.SplittersListResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a new splitter.
func (c *Client) Create(
	ctx context.Context,
	request *extend.SplittersCreateRequest,
	opts ...option.RequestOption,
) (*extend.Splitter, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get details of a splitter.
func (c *Client) Retrieve(
	ctx context.Context,
	// The ID of the splitter to get.
	//
	// Example: `"spl_Xj8mK2pL9nR4vT7qY5wZ"`
	id string,
	request *extend.SplittersRetrieveRequest,
	opts ...option.RequestOption,
) (*extend.Splitter, error) {
	response, err := c.WithRawResponse.Retrieve(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update an existing splitter.
func (c *Client) Update(
	ctx context.Context,
	// The ID of the splitter to update.
	//
	// Example: `"spl_Xj8mK2pL9nR4vT7qY5wZ"`
	id string,
	request *extend.SplittersUpdateRequest,
	opts ...option.RequestOption,
) (*extend.Splitter, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
