// Code generated by Fern. DO NOT EDIT.

package workflow_runs_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	extend "github.com/extend-hq/extend-go-sdk"
	client "github.com/extend-hq/extend-go-sdk/client"
	option "github.com/extend-hq/extend-go-sdk/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestWorkflowRunsListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &extend.WorkflowRunsListRequest{
		NextPageToken: extend.String(
			"xK9mLPqRtN3vS8wF5hB2cQ==:zWvUxYjM4nKpL7aDgE9HbTcR2mAyX3/Q+CNkfBSw1dZ=",
		),
	}
	_, invocationErr := client.WorkflowRuns.List(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWorkflowRunsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWorkflowRunsListWithWireMock", "GET", "/workflow_runs", map[string]string{"nextPageToken": "xK9mLPqRtN3vS8wF5hB2cQ==:zWvUxYjM4nKpL7aDgE9HbTcR2mAyX3/Q+CNkfBSw1dZ="}, 1)
}

func TestWorkflowRunsCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &extend.WorkflowRunsCreateRequest{
		Workflow: &extend.WorkflowReference{
			ID: "wf_1234567890",
		},
		File: &extend.WorkflowRunsCreateRequestFile{
			FileFromURL: &extend.FileFromURL{
				URL: "https://example.com/invoice.pdf",
			},
		},
	}
	_, invocationErr := client.WorkflowRuns.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWorkflowRunsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWorkflowRunsCreateWithWireMock", "POST", "/workflow_runs", nil, 1)
}

func TestWorkflowRunsRetrieveWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &extend.WorkflowRunsRetrieveRequest{}
	_, invocationErr := client.WorkflowRuns.Retrieve(
		context.TODO(),
		"workflow_run_id_here",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWorkflowRunsRetrieveWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWorkflowRunsRetrieveWithWireMock", "GET", "/workflow_runs/workflow_run_id_here", nil, 1)
}

func TestWorkflowRunsUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &extend.WorkflowRunsUpdateRequest{
		Name: extend.String(
			"Invoice #12345",
		),
		Metadata: map[string]any{
			"customerId": "cust_abc123",
			"source":     "email-inbox",
		},
	}
	_, invocationErr := client.WorkflowRuns.Update(
		context.TODO(),
		"workflow_run_id_here",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWorkflowRunsUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWorkflowRunsUpdateWithWireMock", "POST", "/workflow_runs/workflow_run_id_here", nil, 1)
}

func TestWorkflowRunsDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &extend.WorkflowRunsDeleteRequest{}
	_, invocationErr := client.WorkflowRuns.Delete(
		context.TODO(),
		"workflow_run_id_here",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWorkflowRunsDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWorkflowRunsDeleteWithWireMock", "DELETE", "/workflow_runs/workflow_run_id_here", nil, 1)
}

func TestWorkflowRunsCancelWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &extend.WorkflowRunsCancelRequest{}
	_, invocationErr := client.WorkflowRuns.Cancel(
		context.TODO(),
		"workflow_run_id_here",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWorkflowRunsCancelWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWorkflowRunsCancelWithWireMock", "POST", "/workflow_runs/workflow_run_id_here/cancel", nil, 1)
}

func TestWorkflowRunsCreateBatchWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &extend.WorkflowRunsCreateBatchRequest{
		Workflow: &extend.WorkflowReference{
			ID: "wf_1234567890",
		},
		Inputs: []*extend.WorkflowRunsCreateBatchRequestInputsItem{
			&extend.WorkflowRunsCreateBatchRequestInputsItem{
				File: &extend.WorkflowRunsCreateBatchRequestInputsItemFile{
					FileFromURL: &extend.FileFromURL{
						URL: "https://example.com/invoice1.pdf",
					},
				},
				Metadata: &extend.RunMetadata{
					"customerId": "cust_abc123",
				},
			},
			&extend.WorkflowRunsCreateBatchRequestInputsItem{
				File: &extend.WorkflowRunsCreateBatchRequestInputsItemFile{
					FileFromURL: &extend.FileFromURL{
						URL: "https://example.com/invoice2.pdf",
					},
				},
				Metadata: &extend.RunMetadata{
					"customerId": "cust_def456",
				},
			},
		},
	}
	_, invocationErr := client.WorkflowRuns.CreateBatch(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWorkflowRunsCreateBatchWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWorkflowRunsCreateBatchWithWireMock", "POST", "/workflow_runs/batch", nil, 1)
}
