// Code generated by Fern. DO NOT EDIT.

package evaluationsets

import (
	context "context"

	extend "github.com/extend-hq/extend-go-sdk"
	core "github.com/extend-hq/extend-go-sdk/core"
	internal "github.com/extend-hq/extend-go-sdk/internal"
	option "github.com/extend-hq/extend-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// List evaluation sets in your account.
func (c *Client) List(
	ctx context.Context,
	request *extend.EvaluationSetsListRequest,
	opts ...option.RequestOption,
) (*extend.EvaluationSetsListResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Evaluation sets are collections of files and expected outputs that are used to evaluate the performance of a given extractor, classifier, or splitter. This endpoint will create a new evaluation set, which items can be added to using the [Create Evaluation Set Item](https://docs.extend.ai/2026-02-09/developers/api-reference/endpoints/evaluation/create-evaluation-set-item) endpoint.
//
// Note: It is not necessary to create an evaluation set via API. You can also create an evaluation set via the Extend dashboard and take the ID from there. To learn more about how to create evaluation sets, see the [Evaluation Sets](https://docs.extend.ai/2026-02-09/product/evaluation/overview) product page.
func (c *Client) Create(
	ctx context.Context,
	request *extend.EvaluationSetsCreateRequest,
	opts ...option.RequestOption,
) (*extend.EvaluationSet, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve a specific evaluation set by ID. This returns an evaluation set object, but does not include the items in the evaluation set. You can use the [List Evaluation Set Items](https://docs.extend.ai/2026-02-09/developers/api-reference/endpoints/evaluation/list-evaluation-set-items) endpoint to get the items in an evaluation set.
func (c *Client) Retrieve(
	ctx context.Context,
	// The ID of the evaluation set.
	//
	// Example: `"ev_2LcgeY_mp2T5yPaEuq5Lw"`
	id string,
	request *extend.EvaluationSetsRetrieveRequest,
	opts ...option.RequestOption,
) (*extend.EvaluationSet, error) {
	response, err := c.WithRawResponse.Retrieve(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
