// Code generated by Fern. DO NOT EDIT.

package webhook_subscriptions_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	extend "github.com/extend-hq/extend-go-sdk"
	client "github.com/extend-hq/extend-go-sdk/client"
	option "github.com/extend-hq/extend-go-sdk/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestWebhookSubscriptionsListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &extend.WebhookSubscriptionsListRequest{
		NextPageToken: extend.String(
			"xK9mLPqRtN3vS8wF5hB2cQ==:zWvUxYjM4nKpL7aDgE9HbTcR2mAyX3/Q+CNkfBSw1dZ=",
		),
	}
	_, invocationErr := client.WebhookSubscriptions.List(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhookSubscriptionsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhookSubscriptionsListWithWireMock", "GET", "/webhook_subscriptions", map[string]string{"nextPageToken": "xK9mLPqRtN3vS8wF5hB2cQ==:zWvUxYjM4nKpL7aDgE9HbTcR2mAyX3/Q+CNkfBSw1dZ="}, 1)
}

func TestWebhookSubscriptionsCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &extend.WebhookSubscriptionsCreateRequest{
		WebhookEndpointID: "wh_Xj8mK2pL9nR4vT7qY5wZ",
		ResourceType:      extend.WebhookSubscriptionResourceTypeExtractor,
		ResourceID:        "ex_Xj8mK2pL9nR4vT7qY5wZ",
		EnabledEvents: []extend.WebhookSubscriptionEventType{
			extend.WebhookSubscriptionEventTypeExtractRunProcessed,
			extend.WebhookSubscriptionEventTypeExtractRunFailed,
		},
	}
	_, invocationErr := client.WebhookSubscriptions.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhookSubscriptionsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhookSubscriptionsCreateWithWireMock", "POST", "/webhook_subscriptions", nil, 1)
}

func TestWebhookSubscriptionsRetrieveWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &extend.WebhookSubscriptionsRetrieveRequest{}
	_, invocationErr := client.WebhookSubscriptions.Retrieve(
		context.TODO(),
		"webhook_subscription_id_here",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhookSubscriptionsRetrieveWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhookSubscriptionsRetrieveWithWireMock", "GET", "/webhook_subscriptions/webhook_subscription_id_here", nil, 1)
}

func TestWebhookSubscriptionsUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &extend.WebhookSubscriptionsUpdateRequest{
		EnabledEvents: []extend.WebhookSubscriptionEventType{
			extend.WebhookSubscriptionEventTypeExtractRunProcessed,
		},
	}
	_, invocationErr := client.WebhookSubscriptions.Update(
		context.TODO(),
		"webhook_subscription_id_here",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhookSubscriptionsUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhookSubscriptionsUpdateWithWireMock", "POST", "/webhook_subscriptions/webhook_subscription_id_here", nil, 1)
}

func TestWebhookSubscriptionsDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &extend.WebhookSubscriptionsDeleteRequest{}
	_, invocationErr := client.WebhookSubscriptions.Delete(
		context.TODO(),
		"webhook_subscription_id_here",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhookSubscriptionsDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhookSubscriptionsDeleteWithWireMock", "DELETE", "/webhook_subscriptions/webhook_subscription_id_here", nil, 1)
}
