// Code generated by Fern. DO NOT EDIT.

package webhook_endpoints_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	extend "github.com/extend-hq/extend-go-sdk"
	client "github.com/extend-hq/extend-go-sdk/client"
	option "github.com/extend-hq/extend-go-sdk/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestWebhookEndpointsListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &extend.WebhookEndpointsListRequest{
		NextPageToken: extend.String(
			"xK9mLPqRtN3vS8wF5hB2cQ==:zWvUxYjM4nKpL7aDgE9HbTcR2mAyX3/Q+CNkfBSw1dZ=",
		),
	}
	_, invocationErr := client.WebhookEndpoints.List(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhookEndpointsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhookEndpointsListWithWireMock", "GET", "/webhook_endpoints", map[string]string{"nextPageToken": "xK9mLPqRtN3vS8wF5hB2cQ==:zWvUxYjM4nKpL7aDgE9HbTcR2mAyX3/Q+CNkfBSw1dZ="}, 1)
}

func TestWebhookEndpointsCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &extend.WebhookEndpointsCreateRequest{
		URL:  "https://example.com/webhooks",
		Name: "Production webhook",
		EnabledEvents: []extend.WebhookEndpointEventType{
			extend.WebhookEndpointEventTypeExtractRunProcessed,
			extend.WebhookEndpointEventTypeWorkflowCreated,
		},
		APIVersion: "apiVersion",
	}
	_, invocationErr := client.WebhookEndpoints.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhookEndpointsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhookEndpointsCreateWithWireMock", "POST", "/webhook_endpoints", nil, 1)
}

func TestWebhookEndpointsRetrieveWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &extend.WebhookEndpointsRetrieveRequest{}
	_, invocationErr := client.WebhookEndpoints.Retrieve(
		context.TODO(),
		"webhook_endpoint_id_here",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhookEndpointsRetrieveWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhookEndpointsRetrieveWithWireMock", "GET", "/webhook_endpoints/webhook_endpoint_id_here", nil, 1)
}

func TestWebhookEndpointsUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &extend.WebhookEndpointsUpdateRequest{}
	_, invocationErr := client.WebhookEndpoints.Update(
		context.TODO(),
		"webhook_endpoint_id_here",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhookEndpointsUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhookEndpointsUpdateWithWireMock", "POST", "/webhook_endpoints/webhook_endpoint_id_here", nil, 1)
}

func TestWebhookEndpointsDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &extend.WebhookEndpointsDeleteRequest{}
	_, invocationErr := client.WebhookEndpoints.Delete(
		context.TODO(),
		"webhook_endpoint_id_here",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhookEndpointsDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhookEndpointsDeleteWithWireMock", "DELETE", "/webhook_endpoints/webhook_endpoint_id_here", nil, 1)
}
