// Code generated by Fern. DO NOT EDIT.

package evaluationsetitems

import (
	context "context"

	extend "github.com/extend-hq/extend-go-sdk"
	core "github.com/extend-hq/extend-go-sdk/core"
	internal "github.com/extend-hq/extend-go-sdk/internal"
	option "github.com/extend-hq/extend-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// List items in a specific evaluation set.
//
// Returns a summary of each evaluation set item. Use the [Get Evaluation Set Item](https://docs.extend.ai/2026-02-09/developers/api-reference/endpoints/evaluation/get-evaluation-set-item) endpoint to get the full details of an evaluation set item.
func (c *Client) List(
	ctx context.Context,
	// The ID of the evaluation set.
	//
	// Example: `"ev_2LcgeY_mp2T5yPaEuq5Lw"`
	evaluationSetID string,
	request *extend.EvaluationSetItemsListRequest,
	opts ...option.RequestOption,
) (*extend.EvaluationSetItemsListResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		evaluationSetID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Evaluation set items are the individual files and expected outputs that are used to evaluate the performance of a given extractor, classifier, or splitter in Extend. This endpoint will create new evaluation set items in Extend, which will be used during an evaluation run.
//
// **Limit:** You can create up to 100 items at a time.
//
// Learn more about how to create evaluation set items in the [Evaluation Sets](https://docs.extend.ai/2026-02-09/product/evaluation/overview) product page.
func (c *Client) Create(
	ctx context.Context,
	// The ID of the evaluation set.
	//
	// Example: `"ev_2LcgeY_mp2T5yPaEuq5Lw"`
	evaluationSetID string,
	request *extend.EvaluationSetItemsCreateRequest,
	opts ...option.RequestOption,
) (*extend.EvaluationSetItemsCreateResponse, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		evaluationSetID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get details of an evaluation set item.
func (c *Client) Retrieve(
	ctx context.Context,
	// The ID of the evaluation set.
	//
	// Example: `"ev_2LcgeY_mp2T5yPaEuq5Lw"`
	evaluationSetID string,
	// The ID of the evaluation set item.
	//
	// Example: `"evi_kR9mNP12Qw4yTv8BdR3H"`
	itemID string,
	request *extend.EvaluationSetItemsRetrieveRequest,
	opts ...option.RequestOption,
) (*extend.EvaluationSetItem, error) {
	response, err := c.WithRawResponse.Retrieve(
		ctx,
		evaluationSetID,
		itemID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// If you need to change the expected output for a given evaluation set item, you can use this endpoint to update the item. This can be useful if you need to correct an error in the expected output or if the output of the extractor, classifier, or splitter has changed.
func (c *Client) Update(
	ctx context.Context,
	// The ID of the evaluation set.
	//
	// Example: `"ev_2LcgeY_mp2T5yPaEuq5Lw"`
	evaluationSetID string,
	// The ID of the evaluation set item.
	//
	// Example: `"evi_kR9mNP12Qw4yTv8BdR3H"`
	itemID string,
	request *extend.EvaluationSetItemsUpdateRequest,
	opts ...option.RequestOption,
) (*extend.EvaluationSetItem, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		evaluationSetID,
		itemID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete an evaluation set item.
func (c *Client) Delete(
	ctx context.Context,
	// The ID of the evaluation set.
	//
	// Example: `"ev_2LcgeY_mp2T5yPaEuq5Lw"`
	evaluationSetID string,
	// The ID of the evaluation set item.
	//
	// Example: `"evi_kR9mNP12Qw4yTv8BdR3H"`
	itemID string,
	request *extend.EvaluationSetItemsDeleteRequest,
	opts ...option.RequestOption,
) (*extend.EvaluationSetItemsDeleteResponse, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		evaluationSetID,
		itemID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
